### ISSUE TITLE
Running BoxContentSDKSampleApp in Xcode 7 with Swift gives errors ...

### ISSUE THREAD

**Issue by everestman27** [box/box-ios-sdk#111]
Hi,

I am looking to leverage the sample app for a Swift project and followed the instructions for creating a podfile for the BoxContentSDKSampleApp. Later, I updated the code in AppDelegate.m into AppDelegate.swift and added all the user created/UI related .h files in the objective C bridging header. However, I run into a series of a cascading set of issues primarily around header files not being invoked in the .m files. 

Looking for inputs on how to get the BoxContentSDKSampleApp code working in Swift. 

Thanks in advance.

**Comment by boxtcarpel** [comment]
Hi Rajesh,

Thanks for using the SDK and for reaching out. We'll look into this and let you know soon.

**Comment by jdizoglio** [comment]
Hi Rajesh,

Apologies ahead of time for the delay in response.

To add the BoxContentSDK to a swift project,  we should create a new swift project. We can add a Podfile to this new project and work from there.

Preliminary info: I using xCode 7.1 beta and CocoaPods 0.38.2

1) Create the swift project -> New project -> Single Application -> < set project name, i.e. BoxContentSDKSampleApp-Swift > -> set type to swift and save to location

2) In the project folder (BoxContentSDKSampleApp-Swift) create a Podfile with the following info:

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'
pod 'box-ios-sdk', :git => 'git@github.com:box/box-ios-sdk.git'

3) Run pod install and verify if completed without error:
$ pod install
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `box-ios-sdk` from `git@github.com:box/box-ios-sdk.git`
Downloading dependencies
Installing box-ios-sdk 1.0.10 (was 1.0.10)
Generating Pods project
Integrating client project
Sending stats

4) Close the project and open the newly created workspace in the BoxContentSDKSampleApp-Swift folder:

You should see the BoxContentSDKSampleApp-Swift and a Pods projects in the the project navigator of the workspace.

5) Confirm you can build the project. CocoaPods configured the modulemap and umbrella header, this will allow us to call objective-c static library methods as well as message 'category' methods.

6) To consume BoxContentSDK, simply add 'import BoxContentSDK' to your swift files and make calls to the BoxContentSDK interface.

// Snippet of code to test the calls into BoxContentSDK - AppDelegate.swift

import UIKit
import CoreData
import BoxContentSDK

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?

```
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {

    _ = BOXContentClient.self.setClientID("set client id", clientSecret: "set client secret")

    self.window = UIWindow(frame: UIScreen.mainScreen().bounds)
    let navController = UINavigationController()
    let mainView = ViewController(nibName: nil, bundle: nil)

    navController.viewControllers = [mainView]
    self.window!.rootViewController = navController
    self.window?.makeKeyAndVisible()

    return true
}
```

...

// Let me know where else I can be of assistance.
// Regards, Jim

**Comment by boxtcarpel** [comment]
Hello Rajesh,

Hopefully these steps work for you. Please reopen this ticket if you run into any additional issues.

**Comment by saravananNV** [comment]
hi jdizoglio,

```
 first of all thanks to your team for developing this box ios sdk..
 we are integrating this ask into our swift project.we can login using this app and we have to show the images which are in the box.com on our own view controller. we are trying this. can you please help us on this.do we need any token or credentials to achieve that 
```

**Comment by krishnagniyes** [comment]
Hi,

I've followed the same steps but I am getting "Could not build Objective-C module BoxContentSDK". while importing this file AppDelegate.

Please do the needful.

Thanks
Krishna
