### ISSUE TITLE
"The authorization code has expired" error when trying perform authentication challenge

### ISSUE THREAD

**Issue by nhattieunhatkiem** [box/box-ios-sdk#115]
Authorization code was used when bypassing authentication challenge, next time,  when performAuthorizationCodeGrantWithReceivedURL function is called, the authorization code will be expired and cannot be used to get logged in user.

**Comment by boxtcarpel** [comment]
Hi nhattieunhatkiem, Thanks for reaching out and using our SDKs!

I'm not sure I understand the issue you're describing. Can you please try to rephrase what you're seeing? Is there a sample code-block you can provide to clarify?

**Comment by boxtcarpel** [comment]
Hello @nhattieunhatkiem I'm going to close this issue for now. Please do reopen it if you have additional details so that we can help you.
