### ISSUE TITLE
Crash in BOXKeychainItemWrapper.m

### ISSUE THREAD

**Issue by pavanSaberjack** [box/box-ios-sdk#117]
App crashes suddenly once in a while in method
**resetKeychainItem**
at line 210: 
**NSAssert( junk == noErr || junk == errSecItemNotFound, @"Problem deleting current dictionary." );**
Is there any way to avoid this crash/Any update on this issue

**Comment by RicoYao** [comment]
We've seen this before, and it appears to be a Keychain issue with debug builds:

Here is a thread that provides some additional info:
http://stackoverflow.com/questions/22082996/testing-the-keychain-osstatus-error-34018

I don't believe you will encounter this in release builds. Hope that helps.

**Comment by pavanSaberjack** [comment]
Hey @RicoYao ,
Thanks a lot for the reply. 
I ran into this crash in debug builds. But till now haven't got this same crash in Release builds. I will let you know if I get same crash in Release builds.

**Comment by boxtcarpel** [comment]
@pavanSaberjack, thanks for following up. I'm going to close this issue for now. Please feel free to re-open if you see this in the field or want to discuss it further in any way.
