### ISSUE TITLE
Redirect URI mismatch when running sample app

### ISSUE THREAD

**Issue by gcurtis** [box/box-ios-sdk#13]
When running the sample app, I get a redirect_uri mismatch after attempting to login:

![Screenshot of redirect_uri error](http://i.imgur.com/N2dqbm3.png)

I found [some documentation](https://github.com/box/box-ios-content-sdk/blob/060d10abb52d8e7a7c9512f3a36bb9bf861dbd4f/BoxContentSDK/BoxContentSDK/OAuth2/BOXOAuth2Session.h#L64) in BOXOAuth2Session.h that says I must leave the redirect_uri in my app settings blank. However, this is impossible if you've had a redirect URI previously set. Attempting to clear my app's redirect URI in Box gives the error - "OAuth2 redirect URL must specify a valid URL and must not be http://".

Perhaps adding some extra documentation in the sample app indicating what the redirect_uri should be would help.

**Comment by amitegghead** [comment]
It should work if you enter boxsdk-YOUR_CLIENT_ID://boxsdkoauth2redirect into the developer console for your redirect_uri, replacing YOUR_CLIENT_ID with your actual client ID.

**Comment by selvamsankaran** [comment]
For me its not working after adding the content in redirect_uri. Any one have any update...
