### ISSUE TITLE
Unexpected type received while creating BOXMetadata

### ISSUE THREAD

**Issue by alpkeser** [box/box-ios-sdk#132]
Please check the post that I've opened at stackoverflow;

http://stackoverflow.com/questions/33550632/unexpected-value-while-creating-boxmetadata

Thanks!
Alp

**Comment by boxtcarpel** [comment]
Thanks for using the SDK and for reaching out, Alp. We'll take a look.

**Comment by lopopolo** [comment]
`$version` and `$typeversion` are two system keys the metadata team has added in support of schema migrations. There are several issues at play here.
1. When "[Retrieving all custom metadata information (key/value pairs)](https://github.com/box/box-ios-sdk/blob/master/BoxContentSDK/BoxContentSDK/Models/BOXMetadata.m#L45)", the code does the check for system key after it attempts to deserialize the key.
2. The [deserialization code](https://github.com/box/box-ios-sdk/blob/master/BoxContentSDK/BoxContentSDK/Models/BOXMetadata.m#L50) makes the assumption that all keys have string values. This is not true. Valid metadata values also include floats and ints.

It is curious why this code even attempts to deserialize the JSON attributes. It should simply make a copy of the JSONData dictionary and remove the `$` prefixed keys.

**Comment by boxtcarpel** [comment]
Thanks again for catching this issue, it should be resolved by https://github.com/box/box-ios-sdk/pull/134. Please feel free to reopen the issue if you run into further issues.
