### ISSUE TITLE
Downloadable links can't be generated with new sdk

### ISSUE THREAD

**Issue by zelin** [box/box-ios-sdk#139]
I am using following code to create a shareable link to download files for others

```
BOXContentClient *contentClient = [BOXContentClient defaultClient];
BOXFileShareRequest *request = [contentClient sharedLinkCreateRequestForFileWithID:path];
[request setCanDownload:YES];
[request setCanPreview:YES];

[request performRequestWithCompletion:^(BOXFile *file, NSError *error)
{
    if(error != nil)
    {
        [self.mainController.indicator hide];
        [Utilities errorDisplay:error.localizedDescription];
    }
    else
    {
        if (self.shouldDownload)
        {
            [self downloadFileWithPath:file.sharedLink.downloadURL.absoluteString name:self.filename];
        }
        else
        {
            [self.mainController openSharingDialog:file.sharedLink.downloadURL.absoluteString];
        }
    }
}];
```

As can be seen setDownload is Yes

however when link is opened it gives error access denied.

How can i create downloadable link?

**Comment by RicoYao** [comment]
Hi @zelin 

Apologies for the delayed response. I notice in your code that you did not set the "accessLevel" for the shared link request. Depending upon the type of Box account being used, it's possible that the download URL would still be restricted. As a test, could you try setting the accessLevel to "open" when creating the shared link:

[request setAccessLevel:BOXSharedLinkAccessLevelOpen]

Note that setting the accessLevel to BOXSharedLinkAccessLevelOpen means that anyone with the link will be able to access the file. This may or may not have been your intention so I just wanted to note that.
