### ISSUE TITLE
Is there a method to determine if default client is authenticated w/o forcing auth?

### ISSUE THREAD

**Issue by agiletortoise** [box/box-ios-sdk#169]
Is there a way to check if a Box client is authenticated silently?  I'd like to be able to query if auth is present, without triggering the authentication process if it is not.

This is useful in apps that want to be able to give an account status screen to users who may or may not have Box linked for use in the app.

Thanks.

**Comment by boxtcarpel** [comment]
The easiest way to test if a Box client is authenticated is check the user property of the client object,

For example, if you have a BOXContentClient object named client (gotten from [BOXContentClient defaultClient] in the simple case) you can check whether the user property is nil or not to ascertain the auth status as such:
[client user] != nil // This means there is no authenticated user in this session (BOXContentClient).

I hope that helps, please let us know if you have any more questions or need further assistance!

**Comment by agiletortoise** [comment]
That does help, thanks!
