### ISSUE TITLE
App to app login problem

### ISSUE THREAD

**Issue by alexandrhotko** [box/box-ios-sdk#209]
I try to integrate app to app login.
1. Add to info.plist LSApplicationQueriesSchemes with "box-onecloud"
2. Add URL Schemes with "boxsdk-MY_CLIENT_ID"
3. Call [ BOXContentClient setAppToAppBoxAuthenticationEnabled:YES ]; before auth.

After redirect to box app, it show black controller with cancel button. What I'm doing wrong?

**Comment by boxtcarpel** [comment]
Hi @alexandrhotko there is a setting we have to turn on for your application on our backend, before app-to-app auth will begin working for you.
If you give us your client ID, we can get this enabled for you.

If you would rather not do that over GitHub, feel free to contact us directly (https://developers.box.com/help/). Just mention this GitHub issue.

Thanks and good luck.

**Comment by boxtcarpel** [comment]
@alexandrhotko I believe you've been working with support (and I've enabled app to app auth for your app), so you should be good to go. Please let us know if there is anything else we can help with.

**Comment by alexandrhotko** [comment]
Yes, I wrote to support. Now I'm just waiting.
