### ISSUE TITLE
Podfile syntax changed for latest version of Cocoapods

### ISSUE THREAD

**Issue by jpm165** [box/box-ios-sdk#226]
It looks like 'pod install' no longer works unless you specify a target app in the Podfile...

So for example from the Podfile that comes with BoxContentSDKSampleApp:

pod 'box-ios-sdk', :path => '../' #no longer works 
# instead do this

target "BoxContentSDKSampleApp" do
pod 'box-ios-sdk', :path => '../'
end

**Comment by h2kuo** [comment]
Thanks for catching that! We've updated it on our master branch.
