### ISSUE TITLE
Show images on our own view controller using this sdk-ios

### ISSUE THREAD

**Issue by saravananNV** [box/box-ios-sdk#228]
hi jdizoglio,

 first of all thanks to your team for developing this box ios sdk..
 we are integrating this ask into our swift project.we can login using this app and we have to show the images which are in the box.com on our own view controller. we are trying this. can you please help us on this.do we need any token or credentials to achieve that

**Comment by h2kuo** [comment]
Thanks for using our SDK!

Have you looked at the BoxContentSDKSampleApp in this repository yet? The app contains an example of how to authenticate a user, which handles the tokens/credentials through our SDK client. 

You can also look at our documentation for [app setup](https://github.com/box/box-ios-sdk/blob/master/doc/Setup.md) and [authentication](https://github.com/box/box-ios-sdk/blob/master/doc/Authentication.md) as a reference for how to get started. Please let us know if you have any further questions or need help with any of the steps!

**Comment by h2kuo** [comment]
@saravananNV I'm going to close this issue for now, but please feel free to reopen it if you are still experiencing any issues!
