### ISSUE TITLE
Unable to retrieve tags through iOS SDK

### ISSUE THREAD

**Issue by helzapps** [box/box-ios-sdk#234]
Tags seem to be an integral part of identifying certain folders and files or creating groups of content. I'm building an app for a client where they would like to utilize tags to identify certain things, but so far I've been unable to determine how to acquires tags on `BOXFolder` or `BOXFile` objects. 
Here's how I'm making a request for folders contents:

```
    BOXFolderItemsRequest *itemsRequest = [self.client folderItemsRequestWithID:self.folderID];
    itemsRequest.requestAllItemFields = YES;
    [itemsRequest performRequestWithCompletion:^(NSArray *items, NSError *error) {
        if (error == nil) {
            self.items = items;
            [self.carouselView reloadData];
        }
    }];
```

I assumed that by setting the `itemsRequest.requestAllItemsFields = YES` that I would get all fields. But from what I can see, tags is not a property on any of the model objects `BOXModel`, `BOXItem`, `BOXFolder`, `BOXFile`. I also checked the JSON field and the tags field is not in their either. Should the tags be included as a first class citizen and have a property? Or at a minimum included with the JSON data?

This [post](https://community.box.com/t5/Developer-Forum/how-to-get-folder-s-tags-in-iOS-SDK/td-p/16723) eluded that a bug should be filed. I don't see that one was so am filing one just in case.

Thanks
Jordan

**Comment by boxtcarpel** [comment]
Thank you for reaching out and using the SDK. At this time, our current focus at Box is to enhance our 'Metadata' features rather than further investment in 'Tags'. Please check out the metadata functionality of the SDK to see if that fits your needs.

**Comment by helzapps** [comment]
From what I can see metadata only exists for files, or I can only make requests for `BOXFiles`. `metadataAllInfoRequestWithFileID`; `BOXFolders` do not have metadata?
This presents a challenge as the problem I'm trying to solve is the client would like only folders that have been tagged with a specific tag to show up in the app. For programming purposes, even if the `BOXFolder` had metadata which it doesn't appear to as my requests:

```
    BOXFolderItemsRequest *itemsRequest = [self.client folderItemsRequestWithID:self.folderID];
    itemsRequest.requestAllItemFields = YES;
    [itemsRequest performRequestWithCompletion:^(NSArray *items, NSError *error) {
        if (error == nil) {
            self.items = items;
            for (BOXItem *item in items) {
                if ([item isFolder]) {
                    BOXMetadataRequest *metadataInfoRequest = [self.client metadataAllInfoRequestWithFileID:item.modelID];
                    [metadataInfoRequest performRequestWithCompletion:^(NSArray *metadatas, NSError *error) {
                        NSLog(@"Metadata for item: %@,\n%@", item.name, metadatas);
                        if (item == items.lastObject) {
                            [self.carouselView reloadData];
                        }
                    }];
                }
            }
        }
    }];
```

All return (null) for the metadatas array returned on each of these request in the root folder.

I would still have to make a secondary call just to be able to build the structure of folders I'm going to display. This adds extra latency since the info isn't returned with the first call. 

How would you suggest I retrieve only folders tagged with a specific keyword?

**Comment by boxtcarpel** [comment]
Metadata is supported on folders, however the ability to interact with an individual folder's metadata (get/set/delete) is not yet implemented. That needs to be added, I filed https://github.com/box/box-ios-sdk/issues/235 for it.

However, to achieve what you're trying to do, I would suggest checking out our search functionality for metadata. In https://github.com/box/box-ios-sdk/blob/master/BoxContentSDK/BoxContentSDK/Clients/BOXContentClient%2BSearch.h:

> /**
> - Generate a request to search for files and folders in a user's account using metadata tags. You can customize
> - the search by setting properties of the BOXSearchRequest before executing it.
>   *
> - @param templateKey The template to search for metadata tags in
> - @param scope The scope to search for metadata templates in
> - @param filters The metadata tags to filter for
> - @param range An offset (NSRange location) and limit (NSRange limit). The maximum limit allowed is 200, default is 30.
>   *
> - @return A request that can be customized and then executed.
>   */
>   - (BOXSearchRequest *)searchMetadataRequestWithTemplateKey:(NSString *)templateKey
>                                                  scope:(NSString *)scope
>                                                filters:(NSArray *)filters
>                                                inRange:(NSRange)range;

You can then set the 'type' on the request (https://github.com/box/box-ios-sdk/blob/master/BoxContentSDK/BoxContentSDK/Requests/BOXSearchRequest.h) to BOXAPIItemTypeFolder.

Please let us know if that helps and if you have any additional questions.

**Comment by boxtcarpel** [comment]
@helzapps I hope that all makes sense and works well for your needs. I'm closing this issue for now, but please feel free to re-open it or reach out if you have questions or need additional help. Good luck!

**Comment by helzapps** [comment]
Understood. We actually found a way to get the info from the JSON data. We ultimately wrote our own subclassed CoreData model version of the BOXFolder object and added the tags to it.

**Comment by boxtcarpel** [comment]
Glad to hear it, Jordan. Happy it was extensible enough for you. Good luck with your project and let us know if you need additional assistance in the future!

**Comment by bazik123** [comment]
if you are trying to do the same thing the solution is to overwrite the `- (NSArray *)fullFolderFieldsArray` method of BOXRequest and make sure it contains `@"tags"` in addition to all other fields. overwriting a method in a category is terribly ugly, but it does help in this case.
