### ISSUE TITLE
Lock Thread in BoxFileSystem.m after call - (void)refreshAccessTokenIfNeeded.

### ISSUE THREAD

**Issue by akoncevoiDevicepros** [box/box-ios-sdk#236]
Box sdk version - 1.0.11

When I call `- (void)performRefreshTokenGrant:(NSString *)expiredAccessToken withCompletionBlock:(void(^)(BOXOAuth2Session *session, NSError *error))block` in `BOXOAuth2Session` the completitionBlock doesn't be call see:

```
[super performRefreshTokenGrant:expiredAccessToken withCompletionBlock:^(BOXAbstractSession *session, NSError *error) {
            if (expiredAccessToken.length > 0 && error != nil && ![self isInvalidGrantError:error]) {
                [self.expiredOAuth2Tokens removeObject:expiredAccessToken];
            }
        }];
```

For hotFix I insert call completitionBlock. :

```
[super performRefreshTokenGrant:expiredAccessToken withCompletionBlock:^(BOXAbstractSession *session, NSError *error) {
            if (expiredAccessToken.length > 0 && error != nil && ![self isInvalidGrantError:error]) {
                [self.expiredOAuth2Tokens removeObject:expiredAccessToken];
            }
            block(nil,nil);
        }];
```

May be we have another way to fix this problem?

**Comment by RicoYao** [comment]
Hi @akoncevoiDevicepros I believe this may have been fixed in our master branch. Would you mind trying to update to the master?

**Comment by akoncevoiDevicepros** [comment]
Thanks @RicoYao, will you update podspec or create new stable tag?
