### ISSUE TITLE
Having trouble getting the .enterprise value from BoxUser with BOXUserRequest to differenciate between enterprise and personal account

### ISSUE THREAD

**Issue by MaximeBoulat** [box/box-ios-sdk#26]
The .enterprise flag always comes in as nil using both my company's test account. One is personal the other is enterprise. I do have the requestAllUserFields property of the request set to YES.

What am I missing? Thanks.

**Comment by RicoYao** [comment]
Hi @MaximeBoulat, thank you for reaching out. What is the specific request that you are making? (i.e. which request are you setting requestAllUserFields for)

EDITED: Sorry for the redundant question, I see you specified BOXUserRequest in your title. We'll investigate.

**Comment by RicoYao** [comment]
I tried with the following code on an enterprise account, and I was able to retrieve the enterprise from the BOXUser object:

```
    BOXUserRequest *userRequest = [[BOXContentClient defaultClient] currentUserRequest];
    userRequest.requestAllUserFields = YES;
    [userRequest performRequestWithCompletion:^(BOXUser *user, NSError *error) {
        NSLog(@"Enterprise: %@", user.enterprise.name);
    }];
```

Is this similar to what you're doing?

**Comment by MaximeBoulat** [comment]
Hello,

Yes that is exactly what I am doing. Is there a way I can communicate to you the account my company gave me for the box integration directly? Maybe there s something wrong with the account? It does work with the web client.

**Comment by RicoYao** [comment]
Hi @MaximeBoulat could you please send a message through our help portal: https://support.box.com/hc/en-us/requests/new?ticket_form_id=31523

Reference this github issue so we have context, and include the email address of the enterprise account so we can check on it.

**Comment by MaximeBoulat** [comment]
Thank you. I figured out what was wrong. It was on my side. Thanks for the feedback. Closing the issue

**Comment by MaximeBoulat** [comment]
I am having another problem. Now that I am actually getting the .enterprise payload I am crashing when a user is not enterprise!!!!

Because the enterprise value of the JSON is null and when its parsed in BoxUser.m it crashes in 

```

NSDictionary *enterpriseDictionary = [NSJSONSerialization box_ensureObjectForKey:BOXAPIObjectKeyEnterprise
                                                                            inDictionary:JSONResponse
                                                                         hasExpectedType:[NSDictionary class]
                                                                             nullAllowed:NO];

```

I have attached a screenshot of the crash with the JSON payload in the console. Can you confirm that when a BoxUserRequest is configured with requestAllUserFields and the user is non enterprise the JSON does not cause a crash in the parsing of the user?
![screen shot 2015-05-26 at 3 16 57 pm](https://cloud.githubusercontent.com/assets/12277702/7821295/e105af8c-03bb-11e5-9c6f-0e77d3db1aa7.png)

**Comment by RicoYao** [comment]
Thanks for flagging that. We will fix.

**Comment by RicoYao** [comment]
We pushed v1.0.3 of this SDK which contains a fix for this issue. Could you please try updating your pod? Thanks.

**Comment by MaximeBoulat** [comment]
okay thanks it seems good closing the issue.
