### ISSUE TITLE
BOXFileDownloadRequest.performRequestWithProgress(...) not working or producing errors

### ISSUE THREAD

**Issue by rtrevivian** [box/box-ios-sdk#260]
# BOXFileDownloadRequest.performRequestWithProgress(...) does not execute the progressBlack during a download, it does execute the completionBlock but no file is seemingly created and no error is reported.

[BoxPrototype.zip](https://github.com/box/box-ios-sdk/files/468606/BoxPrototype.zip)

**Comment by jdizoglio** [comment]
@rtrevivian - looking into the issue now. At first glance I saw was empty:
BOXContentClient.setClientID("client-id", clientSecret: "client-secret")
Had registered your app with Box dev? 
https://developer.box.com/

Not having an auth session is similar to your issue description. However, I'll proceed to review the code with my credentials and verify. Will keep you posted.

Cheers,
Jim

**Comment by jdizoglio** [comment]
@rtrevivian An status update: I am able to reproduce the issue and nothing to do with credentials. The request is successful and the file item is being returned. However, the response with file data is 0 bytes. I'll let you know what I find.

**Comment by jdizoglio** [comment]
@rtrevivian For now I have work around.
- In your swift class, BoxTableViewController, line 106-115. replace the request with the following. Create the NSOutputStream locally and use the corresponding fileDownloadRequestWithID. There seems to be a problem opening the output stream on the object c side of the SDK. I will post a fix for the SDK once I have a good solution. In the meantime, the following should unblock you.
  
  ```
      let outputStream = NSOutputStream.outputStreamToMemory()
      let downloadRequest = contentClient.fileDownloadRequestWithID(item.modelID, toOutputStream: outputStream)
                  downloadRequest.performRequestWithProgress({ (totalBytesTransferred, totalBytesExpectedToTransfer) in
                      print(totalBytesTransferred, "/", totalBytesExpectedToTransfer)
                      let data = outputStream.propertyForKey(NSStreamDataWrittenToMemoryStreamKey)
                      // TODO: write to file here
                      }, completion: { (error) in
                          guard error == nil else {
                              print(error)
                              return
                          }
                          print("Done", localFilePath, NSFileManager.defaultManager().fileExistsAtPath(localFilePath))
                  })
  ```
- I also think you may want to run 'pod install' or update. The zip contained an sdk version 1 commit back. Nothing critical, but will bring you to TOT.
