### ISSUE TITLE
Syntax error in the example

### ISSUE THREAD

**Issue by killerz99** [box/box-ios-sdk#263]
Get the items in a Box Folder

BOXContentClient *contentClient = [BOXContentClient defaultClient];

> BOXFoderItemsRequest

  *folderItemsRequest = [contentClient folderItemsRequestWithID:@"folder-id"];
[folderItemsRequest performRequestWithCompletion:^(NSArray *items, NSError *error) {
    // If successful, items will be non-nil and contain the list of items; otherwise, error will be non-nil.
}];

**Comment by boxtcarpel** [comment]
Thanks @killerz99 this should now be resolved.
