### ISSUE TITLE
Integrate SDK Manually

### ISSUE THREAD

**Issue by bitsarat** [box/box-ios-sdk#270]
Hi, 
Can you please provide instructions to integrate the SDK manually? I do not have admin rights in my mac (to install ruby, cocoapods etc)

**Comment by jdizoglio** [comment]
Hi @bitsarat ,

We can convert the Sample App Xcode project from pod usage to static library.

The following is an example to convert the SDK’s sample app to use the BOXContentSDK as a static library.

1) Clone the BoxContentSDK from github.
2) Navigate into the box-ios-sdk folder and open the BoxContentSDKSampleApp (BoxContentSDKSampleApp.xcworkspace) in Xcode
3) Delete the file 'Pods.xcodeproj' and folder 'Pods' from the project navigator (move to trash is fine)
4) Select the 'BoxContentSDKSampleApp' project in the project navigator

5) Select the 'BoxContentSDKSampleApp' target and go to the ‘Build Phases’ tab
- Delete the ‘ Check Pods Manifest.lock’, ‘Copy Pods Resources’ and ‘Embed Pods Frameworks’ run scripts.
- Expand ‘Linked Binary With Libraries’ and delete (‘-‘) ‘libPods-BoxContentSDKSampleApp.a’

6) Build BoxContentSDKSampleApp, you will see errors. On build completion, go to BoxContentSDKSampleApp target and got to ‘Build Phases’
- Expand ‘Linked Binary With Libraries’ and add (‘+’) libBoxContentSDK.a

7) We need to change some linker flags. 
- Navigate to BoxContentSDKSampleApp proj -> BoxContentSDKSampleApp target-> Build Settings.
- Search ‘other linker flags’ and for ‘Other Linker Flags’, add 2 flags ‘-ObjC’ and ‘-all_load’. 
- This links category classes found in our BOXContentSDK source to your app. Without this you will get runtime errors for selectors not found when calling category methods.
  8) Not that we are configured and completed converting the project from pods to static library, rebuild the app. Should be a successful build.

Remember to add you credentials in your app delegate to enable oAuth, set:
[BOXContentClient setClientID:@"your_client_id" clientSecret:@"your_client_secret"];

And you good to go.

If this is your own project, drag and drop BoxContentSDKSampleApp.xcodeproj file into your app project navigator and start from step 6.

**Comment by bitsarat** [comment]
cool thanks - I will try this and let you know

**Comment by bitsarat** [comment]
I spent the last week resolving issue related to having sub projects (xcodeproj) under your own project. Here is the Apple bug report : https://forums.developer.apple.com/thread/11237. Do you have another suggestion?

**Comment by jdizoglio** [comment]
As I am not able to replicate, it's going to be a little tough to guess which build setting for you is bringing in device frameworks. I would suggest asking IT to temporarily grant you permission to install pods.
