### ISSUE TITLE
No tokens are returned when authenticating a user

### ISSUE THREAD

**Issue by redserpent7** [box/box-ios-sdk#274]
Hi,

Calling the authenticate API does not return the access and refresh tokens. Why is it different in Android SDK? And how can we get the tokens?

**Comment by boxtcarpel** [comment]
Hi @redserpent7, thanks for using our SDK and reaching out.

The iOS SDK is built to make it easy to connect to Box on iOS, thus token management (including persistence and refreshing in a multi-threaded request environment) is handled by the SDK for free.

The SDK is also open-source so you can use whatever pieces you would like and implement things yourself by taking out the underlying logic we use, if you are so inclined.

If you are interested in using the SDK as-is but also need access to the tokens, this is easily achieved by querying the Content Client once authenticated.
You can get the "session" object from the Content Client, and then the abstract session class exposes the 'accessToken'. You can then check if your session class is a 'BOXOAuth2Session' which it will be if you are not using App Users (https://docs.box.com/docs/app-users). If your session class is of 'BOXOAuth2Session' type, then the 'refreshToken' is exposed.

Please let us know if you have any further questions and good luck!

See:
BOXContentClient
- (BOXContentClient *)defaultClient;
  OR if you support multiple Box accounts being authenticated in your application at once:
- (BOXContentClient *)clientForUser:(BOXUserMini *)user;
  @property (nonatomic, readonly, strong) BOXAbstractSession *session;

BOXAbstractSession
@property (nonatomic, readwrite, strong) NSString *accessToken;
@property (nonatomic, readwrite, strong) NSDate *accessTokenExpiration;

BOXOAuth2Session
@property (nonatomic, readwrite, strong) NSString *refreshToken;

**Comment by redserpent7** [comment]
thanks, that worked.
