### ISSUE TITLE
Xcode 8, Swift getting "Could not build Objective-C module BoxContentSDK"

### ISSUE THREAD

**Issue by krishnagniyes** [box/box-ios-sdk#282]
Hi,

I've followed following steps but I am getting "Could not build Objective-C module BoxContentSDK". while importing this file AppDelegate.

Please do the needful.

Thanks
Krishna

To add the BoxContentSDK to a swift project, we should create a new swift project. We can add a Podfile to this new project and work from there.

Preliminary info: I using xCode 7.1 beta and CocoaPods 0.38.2

Create the swift project -> New project -> Single Application -> < set project name, i.e. BoxContentSDKSampleApp-Swift > -> set type to swift and save to location

In the project folder (BoxContentSDKSampleApp-Swift) create a Podfile with the following info:

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'
pod 'box-ios-sdk', :git => 'git@github.com:box/box-ios-sdk.git'

Run pod install and verify if completed without error:
$ pod install
Updating local specs repositories
Analyzing dependencies
Pre-downloading: box-ios-sdk from git@github.com:box/box-ios-sdk.git
Downloading dependencies
Installing box-ios-sdk 1.0.10 (was 1.0.10)
Generating Pods project
Integrating client project
Sending stats

Close the project and open the newly created workspace in the BoxContentSDKSampleApp-Swift folder:

You should see the BoxContentSDKSampleApp-Swift and a Pods projects in the the project navigator of the workspace.

Confirm you can build the project. CocoaPods configured the modulemap and umbrella header, this will allow us to call objective-c static library methods as well as message 'category' methods.

To consume BoxContentSDK, simply add 'import BoxContentSDK' to your swift files and make calls to the BoxContentSDK interface.

// Snippet of code to test the calls into BoxContentSDK - AppDelegate.swift

import UIKit
import CoreData
import BoxContentSDK

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
var window: UIWindow?

func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {

    _ = BOXContentClient.self.setClientID("set client id", clientSecret: "set client secret")

    self.window = UIWindow(frame: UIScreen.mainScreen().bounds)
    let navController = UINavigationController()
    let mainView = ViewController(nibName: nil, bundle: nil)

    navController.viewControllers = [mainView]
    self.window!.rootViewController = navController
    self.window?.makeKeyAndVisible()

    return true
}

**Comment by jdizoglio** [comment]
Hi Krishna,

A few of comments to start. If you could move from away from a beta xCode version and preferably to xCode 8.1. I believe the primary issue maybe the cocoapods version. Update pods to version 0.39.0 as this fixes quite a bit of build setting in regards module imports.

(redacted my import module comments as they apply only to an objc app)

Let me know the results,
Jim

**Comment by jdizoglio** [comment]
Hi Krishna,

Here is bit more info. I ran across some other dev integration challenges related to xCode signing. So let me share these.

I am on xCode 8.1 and using pods 0.39.0. xCode 8.1 has a nuance with code signing that required a work around for the bundle:
https://forums.developer.apple.com/thread/66538

This entry helped me:
"I had the same problem. I did the following steps, and it sovled. Select Pods in the navigation --> TARGETS --> your BundleName --> Signing(Enable Development Signing) --> Identity(Choose Info.plist File). Then I can run it on my simulator."

Steps to build a swift project with Box Content SDK:
1) Create a new swift project.
2) Clone box-ios-sdk into the root folder of the new project.
The folder would list something like this:
_TestSwiftBoxApp$ ls
TestSwiftBoxApp.xcodeproj	TestSwiftBoxAppTests		box-ios-sdk
TestSwiftBoxApp			TestSwiftBoxAppUITests_

3) Create a Podfile in the same app root folder
Example matches my target app name:
_source 'git@gitenterprise.inside-box.net:Mobile/box-ios-podspecs.git'

use_frameworks!
platform :ios, '9.0'

xcodeproj 'TestSwiftBoxApp.xcodeproj'
link_with 'TestSwiftBoxApp'

pod 'box-ios-sdk', :path => './box-ios-sdk'_
4) Run pod install
5) open the new workspace file. All should build fine except the bundle code signing.
Using the above Apple forum suggestion - Set the dev signing and for the identity info.plist file I selected the corresponding bundle plist suggested in the choose plist step. Seems xCode requires this for resource bundle resolution.

6) Add your Box sdk code to the AppDelegate class. 'import BoxContentSDK' and '_ = BOXContentClient.self.setClientID....'

You should have a successful compile with Box objc frameworks available for you swift app.
