### ISSUE TITLE
Pod install on BoxContentSDKSampleApp doesn't work

### ISSUE THREAD

**Issue by Roshanalexander** [box/box-ios-sdk#294]
When doing pod install on the sample app, the following error is obtained.

Analyzing dependencies
Fetching podspec for `box-ios-sdk` from `../`
[!] Unable to satisfy the following requirements:

- `box-ios-sdk (from `../`)` required by `Podfile`
- `box-ios-sdk` required by `Podfile.lock`

Specs satisfying the `box-ios-sdk (from `../`), box-ios-sdk` dependency were found, but they required a higher minimum deployment target.

**Comment by boxtcarpel** [comment]
@Roshanalexander thank you for using the SDK and for reaching out. Please try again with the latest change, and feel free to close this issue if it works correctly now.

**Comment by Roshanalexander** [comment]
It seems to be fixed. Thanks!
