### ISSUE TITLE
fetchAccessTokenWithCompletion loop

### ISSUE THREAD

**Issue by ed-mejia** [box/box-ios-sdk#297]
Hi there!,

I'm trying to authenticate using access token fetched from my backend, using the following:

`- (void)fetchAccessTokenWithCompletion:(void (^)(NSString *, NSDate *, NSError *))completion`

Everything goes ok if I'm able to get the token but if for some reason I get an error, connection issues or anything then I will try to call the completion block with error something like:

`completion(nil, nil, [[NSError alloc] initWithDomain:@"" code:40000 userInfo:nil]);`

The problem is that I enter in a loop, the controller `BOXFolderViewController` will try to get the token over and over again for ever, how can I stop the `BOXContentClient` to ask indefinitely for the token?

**Comment by crousselle** [comment]
Hi @ed-mejia, 

Thanks you for using our SDK and Box Developer Edition ! 

Could you provide more information about that loop you're witnessing, such as call stacks of the methods that are called continuously ? 

It'd be great if you could provide some sample code of your implementation as well, that would help us identify and track down the issue.

Thank you,

Clement

**Comment by ed-mejia** [comment]
Hi yes, I'm using the **BoxBrowseSDKSampleApp** you can just run the sample app with this view controller instead of the one attached in the sample.
[ViewController.m.zip](https://github.com/box/box-ios-sdk/files/697616/ViewController.m.zip)

**Comment by ed-mejia** [comment]
Hi @crousselle,

Were you able to recreate the issue?, let me know if you need more information.

**Comment by crousselle** [comment]
@ed-mejia thanks for the sample code. I'll come back to you as soon as I can reproduce. 
Thanks !

**Comment by crousselle** [comment]
@ed-mejia thanks for the sample code, I was able to reproduce the issue ! Be on the lookout for a fix soon !

**Comment by ed-mejia** [comment]
@crousselle Great!, looking forward for it 👍

**Comment by crousselle** [comment]
@ed-mejia if you get the latest tag of our BrowseSDK (v1.7.0) (https://github.com/box/box-ios-browse-sdk), this issue should now be fixed.
Thanks for your feedback, feel free to close this issue once verified it is not occurring anymore.

have a great day !
Clement

**Comment by ed-mejia** [comment]
@crousselle AWESOME! Thanks!.

I Can confirm it's working pretty good.

However I was unable to fetch the last tag when installing via cocoapods, doing a fresh install will fetch 1.0.6 instead of 1.0.7 .. tried to update my cocopod repo but the result was the same, I had to point the pod to master in order to be able to get the latest version.
