### ISSUE TITLE
What to put for Scope when calling metadataTemplateInfoRequestWithScope ?

### ISSUE THREAD

**Issue by DeArchiTech** [box/box-ios-sdk#299]
Hello there

I have look through the documentation but I wasn't able to find the info I want.
Specifically, I would like to call this function.

BOXMetadataTemplateRequest *metadataTemplateRequest = [contentClient metadataTemplateInfoRequestWithScope:@"your_scope" template:@"your_template"];

However, I do not know what to put for "your_scope", and I couldn't find any documentations.
If anyone know where to look, please let me know!~

Cheers

**Comment by crousselle** [comment]
Hi @noobiehacker,

Thanks for reaching out ! 

You'll find any documentation about our Metadata APIs here : https://docs.box.com/reference#metadata-object

Thanks,
Clément

**Comment by DeArchiTech** [comment]
Thank you @crousselle , you are very helpful :)
