### ISSUE TITLE
"parent of node to add does not exist" when trying to update metadata

### ISSUE THREAD

**Issue by DeArchiTech** [box/box-ios-sdk#301]
Hey All

I am trying to update the metadata of a file

This is the error I am getting 

**_"parent of node to add does not exist"_**

This is my code

```
    func updateMetaData(fileID : String, completionBlock : BOXMetadataBlock){
        
        let client = BOXContentClient.defaultClient()
        let task : BOXMetadataUpdateTask = BOXMetadataUpdateTask.init(operation: BOXMetadataUpdateADD, path: "/checked", value: "true")
        let request : BOXMetadataUpdateRequest = client.metadataUpdateRequestWithFileID(fileID, template: "poddemo", updateTasks: [task])
        request.performRequestWithCompletion(completionBlock)
        
    }
```

--EDIT

**How I create the MetaData On File**

```
func createMetadataOnFile(fileID : String, completionBlock : BOXMetadataBlock){

        let client = BOXContentClient.defaultClient()
        var task = []
        let metaDataRequest = client.metadataCreateRequestWithFileID(fileID, scope: "enterprise", template: "poddemo", tasks: task as [AnyObject])
        metaDataRequest.performRequestWithCompletion(completionBlock)
        
    }
```

Scheme
<img width="1552" alt="screen shot 2017-01-23 at 11 16 21 am" src="https://cloud.githubusercontent.com/assets/3968317/22218954/cf4030b6-e15d-11e6-913b-7f4bbfd06dbe.png">

<img width="1065" alt="screen shot 2017-01-23 at 11 16 09 am" src="https://cloud.githubusercontent.com/assets/3968317/22218972/e00a1c04-e15d-11e6-961f-f20c631eac3f.png">

Any help is appreciated, thank you!

Cheers

**Comment by crousselle** [comment]
Hi @noobiehacker,

Glad to see you using our Metadata API !
From the sample code & error that you provided, it seems that you're trying to add a value to a non-existent node.
Could you provide more information about your metadata scheme and other places in your code where you call our metadata API ?

Thanks,
Clément

**Comment by DeArchiTech** [comment]
Hey @crousselle 

Thanks for support, I have added more information let me know if you have any other suggested solutions.

David

**Comment by crousselle** [comment]
Hi @noobiehacker,

After taking a closer look, it looks like the path you're providing (`/checked/`) is incorrect. 
According to our API documentation for the endpoint you're using (https://docs.box.com/reference#update-metadata), the API uses a JSON pointer to identify the key to be updated. 

After testing your value (http://www.jsonpointer.com/#/?json=%7B%22checked%22%3A%20%22true%22%7D%0A&pointer=%2Fchecked%2F), it appears that the JSON pointer is incorrect.
By providing the path value as `"/checked"`, the JSON Pointer check passes (http://www.jsonpointer.com/#/?json=%7B%22checked%22%3A%20%22true%22%7D%0A&pointer=%2Fchecked).

I'd suggest to simply change 
`        let task : BOXMetadataUpdateTask = BOXMetadataUpdateTask.init(operation: BOXMetadataUpdateADD, path: "/checked/", value: "true")
`
with 
`
        let task : BOXMetadataUpdateTask = BOXMetadataUpdateTask.init(operation: BOXMetadataUpdateADD, path: "/checked", value: "true")
`

Hope this helps !

Thanks,
Clément

**Comment by DeArchiTech** [comment]
Hey @crousselle 

Thank you for helping out, and you are indeed correct that I have the path wrong.

On a side note, if we set the operations as BOXMetadataUpdateReplace, it won't work if there is nothing to be replace, so we must use BOXMetadataUpdateADD

I will mark this as resolved!

Thanks @crousselle
