### ISSUE TITLE
Assert in BOXContentClient init crashing unintentionally if clientID and client secret not set

### ISSUE THREAD

**Issue by JamesKuang** [box/box-ios-sdk#31]
Hi,

I am getting a crash in `[[BOXContentClient defaultClient] logOut]` and traced it to the singleton not haven't been initialized yet (BOXContentClient `init` crashes from the Assert for clientID and client secret not set). I know the Assert here is well intentioned, however there is a case where calling `logout` before it is initialized that I believe should be accounted for.

Because the BOX SDK supplements most apps as an additional way to import user data, I don't believe it is the primary path of usage. Therefore, the initialization of the BOX singleton should be left until users actually choose to import from BOX in their usage session. This is consistent with the documentation you guys provide, calling `setClientID:clientSecret:` right before actually use the SDK. In this scenario, the BOX singleton may not always be initialized yet, cause the Assert crash if `logout` is called.

I suggest that there should be a way to call logout on BOX that's essentially a no-op, for the case that the user hasn't navigated to using the BOX SDK in the host app (BOX singleton not initialized yet or clientID/secret not set yet).

Update:
I noticed `setClientID:clientSecret:` doesn't actually initialize the singleton but just sets static IDs, so maybe the readme should be explicit that it must be called on app initialization instead.

Thanks.

**Comment by RicoYao** [comment]
Thanks for the feedback. As you noticed in your update, setClientID:clientSecret: is a class method that does not require an instance of BOXContentClient to exist yet. As you suggest, I'll update the README to suggest that setClientID:clientSecret: be called in UIApplicationDelegate.
