### ISSUE TITLE
Image assets on the sample app

### ISSUE THREAD

**Issue by Roshanalexander** [box/box-ios-sdk#324]
I'm implementing BOX SDK on my personal app and I'm currently using folder place holder images present in the BOX SDK sample app.

Is it allowed to use the thumbnail images in the sample app on our personal apps?  Is it copyrighted? Will there be any legal issues if I use the assets on personal apps for implementing BOX SDK?

**Comment by boxtcarpel** [comment]
You may use the thumbnail images provided in your personal app.
More specifically you can see the assets we expose in our Browse SDK (https://github.com/box/box-ios-browse-sdk/tree/master/BoxBrowseSDK/BoxBrowseSDKResources/Icons), which provides UI from Box to be used in your apps. You are free to use those, they are open-source. :)

Good luck!

**Comment by Roshanalexander** [comment]
Thanks for the info! 👍
