### ISSUE TITLE
BOXFolderItemsRequest does not give the size of file.

### ISSUE THREAD

**Issue by js-jung** [box/box-ios-sdk#37]
Hi.

I developing mobile app using box content sdk.
There is one problem, size property of BOXItem always have nil value.
I would check for this problem.

Thanks.

**Comment by achunBOX** [comment]
Hi Jaesung,

I'm unable to recreate this error on our side, can you specify what you're trying to do and how you're using the SDK? Thanks!

**Comment by js-jung** [comment]
```
BOXFolderItemsRequest *request = [self.client folderItemsRequestWithID:path];
[request performRequestWithCompletion:^(NSArray *items, NSError *error) {
    if (error) {
        failure(error);
    }
    else {
        NSMutableArray *contents = [NSMutableArray array];
        for (BOXItem *item in items) {
            item.size; <--- always have nil value
        }
        completion(path, contents, YES);
    }
}];
```

I've been checked JSONObject, It does not have size entry.

**Comment by achunBOX** [comment]
Hi Jaesung,

Can you tell me what the value of the variable "path" is?

Thanks!

**Comment by js-jung** [comment]
"path" is content folder id. It's modelID property in BOXItem class.

Thanks!

**Comment by achunBOX** [comment]
Try setting the request's requestAllItemFields property to YES and it should work!

**Comment by js-jung** [comment]
It was my mistake.
Sorry man.

I resolved issue.
Thanks!

Have a good day.
