### ISSUE TITLE
Umbrella header doesn't match the framework name.

### ISSUE THREAD

**Issue by constantine-fry** [box/box-ios-sdk#415]
The framework can't be build on a machine with a case-sensitive file system, because the umbrella header `BOXContentSDK.h` doesn't match the framework name `BoxContentSDK`.

![screen shot 2017-06-21 at 10 59 32 am](https://user-images.githubusercontent.com/239692/27375911-d88de7ac-5670-11e7-9891-bd5fc0b1933e.png)
<img width="600" alt="screen_shot_2017-06-21_at_10_58_18" src="https://user-images.githubusercontent.com/239692/27375943-eeec73d8-5670-11e7-8460-9f2da25c7429.png">

**Comment by mickael-menu-mantano** [comment]
Was this fix merged into the main repo? I have the same issue, with Carthage and version 2.0.0.
