### ISSUE TITLE
Swift compatibility

### ISSUE THREAD

**Issue by FlorinSVN** [box/box-ios-sdk#428]
Hello is this sdk compatible with swift I have a hard time integrating it.
Do you have a swift sample project ?

**Comment by jdizoglio** [comment]
Here is an overview for swift usage, let me know where else I can help.

To add the Content SDK to your app,

_(Overview of Carthage usage and adding frameworks to your project.  For more detail https://github.com/Carthage/Carthage)_
1) Create a Cartfile in the folder containing your apps project and add the following entry and save:
github "box/box-ios-sdk"

2) Run carthage:
> carthage update --platform iOS

Once this completes, you will have a Carthage folder created with the SDK code checkedout and the  build folder containing the framework. 

3) Drag the built framework from Carthage/Build/iOS into your project (xCode: Project->General->Embedded Frameworks. 

At this point the Content SDK model is available to your project. You can test for a successful build.

4) Here the an example in swift to use the content sdk. import BoxContentSDK should autocomplete which means module is found:

// Snippet of code to test the calls into BoxContentSDK - AppDelegate.swift

import UIKit
import BoxContentSDK

@uiapplicationmain
class AppDelegate: UIResponder, UIApplicationDelegate {
var window: UIWindow?

func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {

_ = BOXContentClient.self.setClientID("set client id", clientSecret: "set client secret")

self.window = UIWindow(frame: UIScreen.mainScreen().bounds)
let navController = UINavigationController()
let mainView = ViewController(nibName: nil, bundle: nil)

navController.viewControllers = [mainView]
self.window!.rootViewController = navController
self.window?.makeKeyAndVisible()

return true
}
