### ISSUE TITLE
How to retrieve access token in iOS native app:

### ISSUE THREAD

**Issue by hotechboy66** [box/box-ios-sdk#434]
How to retrieve access token in iOS native app:

- (void)fetchAccessTokenWithCompletion:(void (^)(NSString *, NSDate *, NSError *))completion
{
#warning Include logic to retrieve access token with the Developer's Edition (App Users) or use Developer Token found at https://developers.box.com/
    completion(@"your_access_token", [NSDate dateWithTimeIntervalSinceNow:1000], nil);
}

Is there a ios SDK to retrieve it ? find a comment ,but the url doesn't exist anymore. 

* More details on how to retrieve access tokens through the Developer's Edition can be found in the link below.
 * https://developers.box.com/developer-edition/

**Comment by boxtcarpel** [comment]
@hotechboy66 thanks for reaching out and for using our SDK!

I believe the documentation you're looking for has moved to: https://developer.box.com/docs/app-users (and https://developer.box.com/docs/service-account)
Thanks for calling this out!

Please let us know if you have further questions. Good luck!
