### ISSUE TITLE
I Authenticate but  error 20003?

### ISSUE THREAD

**Issue by Bharath2r** [box/box-ios-sdk#458]
let contentClient = BOXContentClient.default()
        contentClient?.authenticate(completionBlock: {(_ user: BOXUser,_ error: Error?) -> Void in
       } as! (BOXUser?, Error?) -> Void)

**Comment by boxtcarpel** [comment]
Hi @Bharath2r, thank you for using the SDK. Are you still having issues?

You can reference the 'Quick Start' section of the readme on https://github.com/box/box-ios-sdk, don't forget step 5: [BOXContentClient setClientID:@"your-client-id" clientSecret:@"your-client-secret"];
There are additional details in the various linked sections from that page as well.

If you have any additional questions please let us know. Good luck!

**Comment by abdallaMunzer** [comment]
@boxtcarpel as per this issue, could you please check this question?

https://stackoverflow.com/questions/47018926/why-box-always-returns-20003-boxsdk-error-at-the-first-login
