### ISSUE TITLE
Attempting to load the view of a view controller while it is deallocating is not allowed 

### ISSUE THREAD

**Issue by tanmayGIT** [box/box-ios-sdk#474]
Before the Box uploading option in my app was working perfectly but when I again tried to use it after 2-3 months, I find there is some issue 
I have tried re-installing the API through Pods but no help
This following warning is appearing and button to upload is not working ..

`[Warning] Attempting to load the view of a view controller while it is deallocating is not allowed and may result in undefined behavior (<BOXAuthorizationViewController: 0x7ffb00c9f3c0>)`

Any help would be appreciated.

**Comment by Prithvijutur** [comment]
@tanmayGIT We no longer distribute the SDK via cocoapods. Its likely you have an out of date Pod. Please look at the readme for the latest instructions using Carthage

**Comment by Prithvijutur** [comment]
Closing issue since cocoapods are no longer supported let me know if you still require assistance.
