### ISSUE TITLE
Podspec not using 1.0.15 (last CocoaPods release)

### ISSUE THREAD

**Issue by bkottcamp** [box/box-ios-sdk#480]
The box-ios-sdk pod spec (box-ios-sdk.podspec.json) at https://cocoapods.org/pods/box-ios-sdk is pointing to version 1.0.14

Please update it to use version 1.0.15

**Comment by jdizoglio** [comment]
@bkottcamp We recommend migrating to the latest v1.1.1. Switching to Carthage should be straight forward. We currently don't have support to complete updates for the spec and project to support cocoapods.
