### ISSUE TITLE
Confusion regarding box-ios-sdk-v2 vs box-ios-sdk

### ISSUE THREAD

**Issue by ashokds** [box/box-ios-sdk#482]
I am in process of integrating Box-ios-sdk with cocoapods. There are two pods to consider:

- https://cocoapods.org/pods/box-ios-sdk-v2 
   Unofficial/Maintained by Unclaimed, last update Dec-2014
   Points to broken github v2 repo: https://github.com/box/box-ios-sdk-v2
- https://cocoapods.org/pods/box-ios-sdk (Maintained by Tom Carpel, Box Inc., last update sept 2016)
   
Is `box-ios-sdk` the most recent version of SDK to use for iOS apps?

There are other repos/SDK that refers to v2 and adds to the confusion. (E.g. https://github.com/box/box-windows-sdk-v2)
And some online posts: https://stackoverflow.com/questions/20013667/box-ios-sdk-v2-search-functionality 

Is there a migration guide for upgrading BoxSDK to newer version? 
Current code base is using:
- `BoxAuthorizationViewController`: Found `BOXAuthorizationViewController` as alternative in box-ios-sdk. The delegate `BoxAuthorizationViewControllerDelegate` isn't present.
- `BoxItemPickerViewController`, can't locate corresponding class yet.
- `BoxItemPickerHelper`, can't locate corresponding class yet.

These classes doesn't exist in the v1.1.1. A link to migration guide would be very helpful. Thanks in advance.

**Comment by ashokds** [comment]
I am planning to use v1.1.1
https://github.com/box/box-ios-sdk/tree/v1.1.1

**Comment by jdizoglio** [comment]
@ashokds We have a readme for authentication: https://github.com/box/box-ios-sdk/blob/master/doc/Authentication.md

BoxItemPicker* class are now part of the browse SDK. https://github.com/jdizoglio/box-ios-browse-sdk

**Comment by ashokds** [comment]
Hi @jdizoglio , 

I'm migrating the code step by step, referring to docs as needed. Looking at other samples/repos as needed: https://github.com/box?utf8=%E2%9C%93&q=box-ios&type=&language=

BoxItemPicker* classes aren't part of following BoxBrowseSDK source tree (searched various releases/versions): 
https://github.com/jdizoglio/box-ios-browse-sdk/tree/v1.0.0/BoxBrowseSDK/BoxBrowseSDK
Must be renamed to BOXItems*.

Slower process so far as it's missing sourcecode history, ios-sdk changelog and migration guides

**Comment by jdizoglio** [comment]
@ashokds What version of the box-ios-sdk are you upgrading from?

**Comment by ashokds** [comment]
@jdizoglio It's was fork of https://github.com/pushkarsingh/box-ios-sdk-v2 based on http://box.github.io/box-ios-sdk-v2/
Forked ~4 years back.

**Comment by jlawton** [comment]
I know I'm coming into this late. This answer to this is that `box-ios-sdk-v2` was never Box-owned, and `box-ios-sdk` was the way to get the Box SDKs using CocoaPods. We currently aren't maintaining and podspecs for the SDKs, and generally advise people to use Carthage or link the SDK manually (which is a simple drag-and-drop in most cases).

Please open a new issue if you have further questions.
