### ISSUE TITLE
authentication response 403 error

### ISSUE THREAD

**Issue by hotechboy66** [box/box-ios-sdk#483]
hi ,we have a token to authenticate ,but response 403 error, may I know why? 
And from website , they have a process to preview a box file with params: token and fileID ,but I didn't found a way to do that in iOS SDK. We have to authenticate firstly then preview a file . Is there another way to preview a file with a token&fileID in iOS SDK ? thx.

**Comment by hotechboy66** [comment]
plus :  we have problem 403 error for some type of box files : 
fileID: 249335838836 . 
token (for preview) : 1!ySfhlDJzfwfygl2QFh05KSF-8ikv9B6icERU_tA9dZorCZv5UCjSDkEd0yKVblXlsoHX9mGDDOcVQB7vVe8oqh4XYn8Dzgr7iYf3z6ZezoylfRtDMttZ7YAE60ZBKWryEOAWHWnU4UY8msV1nrU5sP7uzjiNE_CilAKwDBy83peuwJ67EEG7upjbdzv2wxEXYL1lDwSrABsOchn83Yyxwm4F1NI4nCYduPPjkruZJeuJkMfeL7NyDyO1jxKP2gs8A983QaixffbgUSr3wp1QRmEIMCZ8f_8TcjGpBC6CAtd_5-I9skQfgA4lybZo4Lh-xhKaSQxcpENQ0q7eYJw8ng7xL5oU.

**Comment by jdizoglio** [comment]
Hi @hotechboy66, our Content SDK allows you to use Box. It gives you functionality like file information, download, upload, delete, comment.... To preview a file you will need to also include the Preview SDK (https://github.com/box/box-ios-preview-sdk). The alternative would be to download the file and create you own file viewer.

**Comment by wangqiwei66** [comment]
hi @jdizoglio , I've use both iOS-BOX-SDK and Box-Preview-SDK . 
I wonder how can I use a fileID and a preview token to preview a box file ? Should I ask Preview-SDK team for help  ?

**Comment by DigitalSolomon** [comment]
Please refer to the Preview SDK (https://github.com/box/box-ios-preview-sdk).
