### ISSUE TITLE
Latest master code is not compatible with PreviewSDK 1.1.5

### ISSUE THREAD

**Issue by MattKiazyk** [box/box-ios-sdk#502]
With the change to `BOXRepresentationImageDimensions` the preview SDK no longer compiles as it still has the old `BOXRepresentationDimensions`

https://github.com/box/box-ios-sdk/commit/871228bdbb0cd1960dff518f2be9cdd7d33979d0#diff-5481edd9dd10647655d7d7c67ca69335R24

Can we please get the PreviewSDK updated with the new name?

Thanks

-Matt

**Comment by RLEE0731** [comment]
Hi @MattKiazyk thank you for raising the compatibility issue, we’d advise to use or pull from one of our published releases, as those are verified to be stable. v1.1.3 is now available and should be compatible with PreviewSDK 1.1.5.
