### ISSUE TITLE
Use of undeclared identifier 'SHA_DIGEST_LENGTH' in BOXHashHelper

### ISSUE THREAD

**Issue by erychagov** [box/box-ios-sdk#536]
I can't compile a BoxContentSDK using the Xcode 10 beta:
```
/Users/user/box-ios-sdk/BoxContentSDK/BoxContentSDK/External/HashHelper/BOXHashHelper.m:144:17: Use of undeclared identifier 'SHA_DIGEST_LENGTH'
```

macOS High Sierra 10.13.4
Version 10.0 beta (10L176w)

**Comment by RLEE0731** [comment]
@erychagov thanks for report and fixing this issue! Your pull request has been merged!
