### ISSUE TITLE
Memory leaks from requests causing completionBlock to be retained indefinitely

### ISSUE THREAD

**Issue by vinceplusplus** [box/box-ios-sdk#55]
Hi,

I am using this SDK for a mobile app project. However, after performing some requests, captured objects from my completion blocks don't seem to get released. Digging into the SDK's source code, I found out a couple of retain cycles. Most of them retain strong self in the success handlers. One of them doesn't set a recursive __block block to be nil after use. Please refer to a dirty fix commit below for the troubling lines

https://github.com/vinceplusplus/box-ios-sdk/commit/645313306b53b14f717bb439d96e5990f956f6ae

Thanks

**Comment by achunBOX** [comment]
Thanks for pointing this out! I've opened a PR for a fix and linked it below. Please let us know if you find any other issues.

https://github.com/box/box-ios-sdk/pull/59
