### ISSUE TITLE
Authenticating AppUser

### ISSUE THREAD

**Issue by rpelorosso** [box/box-ios-sdk#550]
Hi! I'm trying to authenticate my AppUser in the application to retrieve files and folders from its account. I have created a Custom Application, and I'm using the following Swift code:

 ```
BOXContentClient.self.setClientID(myClientId, clientSecret: myClientSecret)

let c: BOXContentClient = BOXContentClient.default()

print "Trying to authenticate"

c.autheticateAppUser { (user, error) in

    print("Authentication request done")
    print(user)
    print (error?.localizedDescription)

}
 ```

The problem is that the function is doing nothing. It's not executing the block code, and according to Charles proxy it's not even making any request.

How can I authenticate a UserApp? Isn't this the correct way?

thank you! 

PS: autheticateAppUser is the actual name of the function, so I guess the library has a typo?

**Comment by ric0liva** [comment]
Hello. 
For the correct way please have a look at 
https://github.com/box/box-ios-sdk/blob/master/doc/AppUsers.md
which has some examples on how to authenticate App-user.

A requirement is that the client accessTokenDelegate be set to a class that adopts the BOXAPIAccessTokenDelegate protocol.    Are you setting this prior to calling authenticateAppUser ?

**Comment by rpelorosso** [comment]
Oh no, I wasn't. Thank you for the link. I'll follow the directives there, port it to Swift and give it a go. Thank you!
