### ISSUE TITLE
Code signing "BoxContentSDK.framework" failed.

### ISSUE THREAD

**Issue by aronnelson** [box/box-ios-sdk#557]
How do I get past this? In Xcode 10 (beta). When I try to submit to app store, I get "Code signing "BoxContentSDK.framework" failed.".

Thanks in advance for any help.

**Comment by aronnelson** [comment]
Wasted time on this. You need to do this!

USE THIS PAGE FOR IOS:
https://github.com/Carthage/Carthage/blob/5fd867c4895b4f59d70181dec169a1644f4430e3/README.md#if-youre-building-for-ios


The current linked info will not work.

**Comment by jbarros35** [comment]
this is only valid for Carthage how do you fix that using CocoaPods?

**Comment by aronnelson** [comment]
As far as I know you need to give up on CocoaPods. There is no updated version AFAIK. But, you can mix carthage with CocoaPods which is what I did. But please follow the instructions I linked. GOOD LUCK!
