### ISSUE TITLE
Missing requestAllFile/FolderFields for some requests

### ISSUE THREAD

**Issue by vinceplusplus** [box/box-ios-sdk#56]
Hi,

It seems that some requests returning BOXFile/BOXFolder instances do not have a request-all-fields field. Some of them do return complete information and some of them don't. This makes it a bit inconsistent

BOXFolderCreateRequest
BOXFileUploadRequest
BOXFileUploadNewVersionRequest
BOXFolderCopyRequest
BOXFileCopyRequest

Thanks

**Comment by RicoYao** [comment]
Thanks, we will fix.

**Comment by achunBOX** [comment]
Addressed in the PR linked below.

https://github.com/box/box-ios-sdk/pull/58
