### ISSUE TITLE
Login page not open on first launch

### ISSUE THREAD

**Issue by suniljakhar** [box/box-ios-sdk#562]
There seems to be a problem with this app

Error: Invalid client

Show Error Details
responce_type=code
redirectUri= boxsdk-(null)://boxsdkoauth2redirect
state=z0wu.......djr8=
cle=ient_id=(null)

comes when launch app first time ,after killing app it works fine.
My code is in swift and setting client id secret as documented here.

**Comment by RLEE0731** [comment]
Hi suniljakhar thanks for letting us know, are you setting the client ID and secret prior to calling the authentication function?

**Comment by suniljakhar** [comment]
Hi RLEE0731 , Yes we setting the proper client ID and secret prior to calling the authentication function. As i previously mentioned that first time it is not working but after quit and launch things are working as expected.

**Comment by RLEE0731** [comment]
Does the same behavior happen when you try running the sample app? Make sure to set the client ID and secret under [application:didFinishLaunchingWithOptions:]

**Comment by suniljakhar** [comment]
I am getting this error when trying to run the sample app on device **"Provisioning profile "iOS Team Provisioning Profile: *" doesn't support the App Groups capability."**. Also tried on simulator it is working as expected.

**Comment by RLEE0731** [comment]
Cool, so it seems somewhere in the code is accessing BOXContentClient before the client ID and secret are set. I would say try adding breakpoints wherever BOXContentClient is being called, and ensure [BOXContentClient setClientID:clientSecret:] is first to be called when you run your app.

**Comment by PreciselyAlyss** [comment]
@suniljakhar Are you still running into this issue?
