### ISSUE TITLE
Get thumbnails for PDF files

### ISSUE THREAD

**Issue by rpelorosso** [box/box-ios-sdk#566]
Hi!

When I ask for thumbnails for image files it's working fine, but it looks like PDF files are not supported.  Rather than the correct thumbnail, I'm receiving a PDF icon image. Is there any way to get thumbnails to PDF files, or is it not supported?

thank you! 
Rodrigo

**Comment by jlawton** [comment]
I believe that the older preview APIs didn't support this. I'm working on an update now that will allow you access to the newer representations API. This might require some code changes on your end, but PDF thumbnails are definitely supported through that.

**Comment by rpelorosso** [comment]
Excellent, thank you @jlawton ! I'll pay attention to the new updates, then.

**Comment by PreciselyAlyss** [comment]
@jlawton Was this covered by [PR#565](https://github.com/box/box-ios-sdk/pull/565)? If so, this issue can be closed out.

**Comment by jlawton** [comment]
Yes. Thumbnail Representations are available for PDFs now.
