### ISSUE TITLE
Downloaded videos have zero duration

### ISSUE THREAD

**Issue by BaileyM** [box/box-ios-sdk#569]
I am using BOXFileDownloadRequest to download mp4 videos, and the downloads succeed, but when I inspect the video duration using AVPlayerItem, the duration is nan.  When I play the videos using AVPlayerLayer, they just display the first frame of the video.

For the download, I create a BOXContentClient.forNewSession(), authenticate using my developer token, create a download request using contentClient.fileDownloadRequest, and then call perform.  The progress reports the file size I expect, and the video plays fine in app.box.com, so it does not seem to be a problem with the file.

Is there anything special that needs to be done before or after downloading videos to fix the duration?

**Comment by jlawton** [comment]
There should be nothing to do. Can you verify that the resulting file on disk has the correct size and maybe also check the SHA1? (You can fond the SHA1 of the uploaded file in the BOXFile object). It sounds to me like a problem with the files themselves.

**Comment by BaileyM** [comment]
Fixed, it was an unrelated playback issue on my end, sorry for the false alarm.
