### ISSUE TITLE
BOXFileUploadNewVersionRequest missing contentModifiedAt field

### ISSUE THREAD

**Issue by vinceplusplus** [box/box-ios-sdk#57]
Hi,

The said request is missing the contentModifiedAt field while BOXFileUploadRequest has it. The older SDK also has it

Thanks

**Comment by RicoYao** [comment]
Thanks, we will fix.

**Comment by achunBOX** [comment]
Hi, according to the documentation link below, it doesn't seem like uploading a new version of the same file should support a contentModifiedAt field. Could you link me the file from the previous SDK that allows this? Thanks!

https://box-content.readme.io/reference#upload-a-new-version-of-a-file

**Comment by vinceplusplus** [comment]
Hi,

Could be my bad, I didn't look up the current documentation. However, according to the old SDK, to upload/overwrite we will use **BoxFilesRequestBuilder** which is derived from **BoxItemsRequestBuilder**

https://github.com/box/deprecated-box-ios-sdk/blob/master/BoxSDK/RequestBuilders/BoxItemsRequestBuilder.h

It has a field called **contentModifiedAt** which has the following as part of its comment:

"This property is only settable on item creation or **the creation of new item versions**"

Thanks

**Comment by achunBOX** [comment]
Hi @vinceplusplus ,

Currently, changing the contentModifiedAt field is not an intended functionality in our API for uploading new versions of a file. 

Please let me know if you have any additional questions!

**Comment by vinceplusplus** [comment]
Thanks for the answer, but may I know why it is not an intended functionality?
