### ISSUE TITLE
Image not found when BoxPreviewCoreSDK.framework added in to project

### ISSUE THREAD

**Issue by knollyReddy** [box/box-ios-sdk#580]
when try to build the project i am getting this error in xcode
dyld: Library not loaded: @rpath/BoxPreviewSDK.framework/BoxPreviewSDK
  Referenced from: /Users/knolly/Library/Developer/CoreSimulator/Devices/6B673B4B-52EE-4620-9F38-4C07EE01FAB3/data/Containers/Bundle/Application/F037083D-3DFB-4266-BCAE-A330DCEA0FF7/BOXDemo.app/BOXDemo
  Reason: image not found

Please thanks

**Comment by jlawton** [comment]
It looks like you're importing `BoxPreviewSDK` but not embedding it in your app. BoxPreviewCoreSDK is used by BoxPreviewSDK, so you'll want to embed both.

The simplest way to do that is to drag the frameworks into your project's _Linked Frameworks and Libraries_, then add a script phase to run `carthage copy-frameworks`, giving all the frameworks as input files (see 
https://github.com/Carthage/Carthage#quick-start).

**Comment by knollyReddy** [comment]
I tried all the ways, I added framework in buildphases and added run script and also added input and output file as per the carthage 
i have been added those two frame works in embedded binaries

if possible , please let me know this SDK is available in POD also

**Comment by wangqiwei66** [comment]
RootCause found:
1, in code, accessTokenDelegate always returns , not setted:
#pragma mark - access token delegate
- (id<BOXAPIAccessTokenDelegate>)accessTokenDelegate
{
    return self.queueManager.delegate;
}
2, I found that after I set the delegate , client.accessTokenDelegate and queue.delegate always nil:
<img width="925" alt="image" src="https://user-images.githubusercontent.com/23308747/50875987-c7bdaf80-1405-11e9-8cd6-d2aa74b15ca0.png">
That cause the delegate func never be called.

**Comment by knollyReddy** [comment]
@wangqiwei66 can you provide code for how to access the BOX by using accesstoken and file_id

**Comment by mattwiller** [comment]
@knollyReddy It looks like there are a few other comments here that seem to indicate that this may no longer be an issue for you — are you still having trouble loading the BoxPreviewSDK?
