### ISSUE TITLE
Single User Mode authenticaion always present an error: redirect_url_mismatch.

### ISSUE THREAD

**Issue by wangqiwei66** [box/box-ios-sdk#583]
When I authenticate boxClient, always present a view to show error like this: 
<img width="327" alt="image" src="https://user-images.githubusercontent.com/23308747/51154425-b3b6f980-18ae-11e9-9e3f-639f6c255d86.png">
I wonder why? 
And following is the code : 
<img width="846" alt="image" src="https://user-images.githubusercontent.com/23308747/51154486-dd702080-18ae-11e9-95b6-f213f6844c16.png">

<img width="969" alt="image" src="https://user-images.githubusercontent.com/23308747/51154468-cf220480-18ae-11e9-9ada-ac6e6e342da5.png">

**Comment by wangqiwei66** [comment]
Error details:

<img width="277" alt="image" src="https://user-images.githubusercontent.com/23308747/51154559-317b0500-18af-11e9-8d4b-d979c2f6fa8b.png">

**Comment by Prithvijutur** [comment]
@wangqiwei66 Did you setup a custom redirect uri in developer settings? In that case you might have to use this to intialize [contentClient](https://github.com/box/box-ios-sdk/blob/f815c01b734a903a8e2c3d3dd02ec4bcdfda93e2/BoxContentSDK/BoxContentSDK/Clients/BOXContentClient.h#L176)

**Comment by wangqiwei66** [comment]
> @wangqiwei66 Did you setup a custom redirect uri in developer settings? In that case you might have to use this to intialize [contentClient](https://github.com/box/box-ios-sdk/blob/f815c01b734a903a8e2c3d3dd02ec4bcdfda93e2/BoxContentSDK/BoxContentSDK/Clients/BOXContentClient.h#L176)

Maybe I didn't config the redirect url correctly. I intend to use contentCLient , the appUser way . But authentication method never callback.

**Comment by wangqiwei66** [comment]
@jdizoglio you updated 2.2.0 for better appUser use. Can you follow this appUser critical ERROR? Appuser CAN NOT use in 2.2.0 !!!!!!

**Comment by jdizoglio** [comment]
@wangqiwei66 Our platform team is currently looking into their code change and should get back to you soon.

**Comment by mattwiller** [comment]
@wangqiwei66 As I mentioned in #582, I've just updated https://github.com/box/box-ios-sdk/blob/master/doc/BoxPlatform.md — it should now contain working sample code in both Swift and Objective-C for instantiating a client using Server-to-Server auth.  If you follow the examples given there, does this problem still occur for you?
