### ISSUE TITLE
Get Representation does not work for word and excel

### ISSUE THREAD

**Issue by ManasaMS85** [box/box-ios-sdk#590]
BOXRepresentationHints API - has only 3 options -
extern const BOXRepresentationHints BOXRepresentationHintsDefaultThumbnails;
/// A good preview for most file types. Maybe more than one preview representation
/// (currently at least the first available of PDF, HLS, MP4, MP3 or JPG)
extern const BOXRepresentationHints BOXRepresentationHintsDefaultPreview;
/// Both thumbnails and the preview defined above
extern const BOXRepresentationHints BOXRepresentationHintsDefaultThumbnailsandPreview;

I need to show high quality image and pdf, word and excel's first page - the option selected - BOXRepresentationHintsDefaultPreview works for images and PDF but doesnot work for word and excel . Is their any way or API which gives me all of these options

**Comment by ManasaMS85** [comment]
The Previous version of SDK had support for Word and Excel

**Comment by mattwiller** [comment]
@ManasaMS85 You can pass any arbitrary string of representation hints, and do not need to reply on the defaults provided.  Please see the [Representations API documentation](https://developer.box.com/v2.0/reference/#section-x-rep-hints-header) for more information and examples of how to construct the hints string.

If you want both a high-res image and PDF, something like `"[pdf][png?dimensions=2048x2048]"` might work for you

**Comment by jlawton** [comment]
As Matt points out, you can select your representations with a custom string.

The way that representations work, they will only include the formats that Box converts to. If you actually want the original Word or Excel file, representations are not what you want. There's a download API for that.

**Comment by ManasaMS85** [comment]
@jlawton  - i do not want the original Word or Excel file representation. All i was telling was -   BOXRepresentationHintsDefaultPreview does not convert word doc and excel files representation to PDF

The enum BOXRepresentationHintsDefaultPreview - does the same, it should represent any PDF, word, excel in the PDF representations - Which is not working 

/// A good preview for most file types. Maybe more than one preview representation
/// (currently at least the first available of PDF, HLS, MP4, MP3 or JPG)
extern const BOXRepresentationHints BOXRepresentationHintsDefaultPreview; 

As well coming to @mattwiller  suggestion - Setting the string : "[pdf][png?dimensions=2048x2048]"
throws below error:

fileInfoRequest?.representationHints = "[pdf][png?dimensions=2048x2048]"

Error Domain=com.box.contentsdk.errordomain Code=404 "(null)" UserInfo={com.box.contentsdk.jsonerrorresponse={
    code = "not_found";
    "help_url" = "http://developers.box.com/docs/#errors";
    message = "The given asset path is unsupported for 'png_paged_2048x2048' representation.";
    "request_id" = pbbtv9g07vlzjbi4;
    status = 404;
    type = error;
}}

Individually the PDF works fine and the PNG works fine

**Comment by mattwiller** [comment]
@ManasaMS85 It looks like the PNG representation is causing issues because it's a multi-asset representation (one image per page of the document).  You may need to specify that you want the un-paged version with hints like this: `[pdf][png?dimensions=2048x2048&paged=false]`

**Comment by jlawton** [comment]
@ManasaMS85 I expect the default preview representations to include PDF. If this is not happening, then this is an API bug. We will attempt to reproduce the problem and forward the bug in that case. I'm glad, at least, that the representations are working individually for you.

**Comment by ManasaMS85** [comment]
@jlawton  - Word and Excel was not showing up on the PDF option individually as well. Representation with string "[pdf][png?dimensions=2048x2048&paged=false]"  was not working together because of paged issue as @mattwiller  pointed. 

Neither this change helped me to fetch the representation of word and excel - ideally "BOXRepresentationHintsDefaultPreview"  should have fetched it

**Comment by ManasaMS85** [comment]
@jlawton  - Could you check this issue at your end - representation of word and excel?

**Comment by mattwiller** [comment]
@ManasaMS85 Could you provide us the ID of a Word or Excel file where the PDF representation is not available, so we can look into the issue on our end?

**Comment by ManasaMS85** [comment]
file id for an excel : 403122468801

**Comment by jlawton** [comment]
Matt will follow up, but I did check on some documents I own, and representations works as expected, so it appears not to be a general problem.

**Comment by mattwiller** [comment]
@ManasaMS85 I'm currently checking with our internal Conversion team to see if there's any issue with how the PDF representation is created for that file.

**Comment by mattwiller** [comment]
@ManasaMS85 Our server logs indicate the a PDF representation was correctly generated for that file on Feb. 15th.  Is this file still not working for you?  If possible, can you make the API request for representations manually and let us know what the response looks like?  You can use a tool like [Postman](https://www.getpostman.com/) or the following `curl` command:

```
curl -H "Authorization: Bearer PASTE_ACCESS_TOKEN_HERE" \
-H "X-Rep-Hints: [pdf]" \
https://api.box.com/2.0/files/403122468801?fields=representations
```

**Comment by ManasaMS85** [comment]
{"type":"file","id":"403122468801","etag":"0","representations":{"entries":[{"representation":"pdf","properties":{},"info":{"url":"https:\/\/api.box.com\/2.0\/internal_files\/403122468801\/versions\/426246046401\/representations\/pdf"},"status":{"state":"success"},"content":{"url_template":"https:\/\/public.boxcloud.com\/api\/2.0\/internal_files\/403122468801\/versions\/426246046401\/representations\/pdf\MN-C02V6269HTD8:AllstateMobMN-C02V6269HTD8:AllstateMN-C02MN-C02V6269HMN-C02 

Not sure why the same thing does not work in the app

**Comment by mattwiller** [comment]
@ManasaMS85 What does the code you're using to get the representations using the SDK look like, and what results does that code produce?  It seems like the API side of things is fine, so perhaps this is an issue with how the SDK is making the API request or interpreting the results.

**Comment by ManasaMS85** [comment]
@mattwiller - Below is code which is used to fetch the image rep \ PDF \Word Rep 
This code works perfectly fine for image and PDF. But when it comes to word or excel -    fileInfoRequest?.perform(completion: { (file: BOXFile?, error: Error?) in itself does not complete - it exits out immediately and doesnt hit completion block at all. So it doesn't reach till getting representations

CODE:

                let fileInfoRequest = boxContentClient.fileInfoRequest(withID: inFile.modelID)
                fileInfoRequest?.requestAllFileFields = true
                fileInfoRequest?.representationHints = BOXRepresentationHintsDefaultPreview
                fileInfoRequest?.perform(completion: { (file: BOXFile?, error: Error?) in
                    if let error = error {
                        print("[BOX] [Error] Error getting file representation info for '\(inFile.modelID)': \(error).")
                        failure(error)
                        return
                    }
                    guard let file = file else {
                        print("[BOX] [Error] Error getting file representation info for '\(inFile.modelID)': No value returned.")
                        failure(BoxServiceError.noValueReturned)
                        return
                    }
                    
                    let outputStream = OutputStream.toMemory()
                    let fileRepresentation = self.boxContentClient.fileRepresentationDownloadRequest(withID: file.modelID, to: outputStream, representation: file.representations.first as? BOXRepresentation)
                    fileRepresentation?.perform(progress: { (bytesDownloaded: Int64, bytesTotal: Int64) in
                        let percentage = Float(bytesDownloaded) / Float(bytesTotal)
                        progressUpdate(percentage)
                    }, completion: { (error: Error?) in
                        if let error = error {
                            failure(error)
                            return
                        }
                        if let data = outputStream.property(forKey: Stream.PropertyKey.dataWrittenToMemoryStreamKey) as? NSData {
                            self.representationCache.setObject(data, forKey: file.sha1 as NSString)
                            completion(data as Data)
                            return
                        }
                        failure(BoxServiceError.noValueReturned)
                    })
                })

As well - We have android version as well "PDF representation was correctly generated for that file on Feb. 15th."- Could you please check if its android or ios

**Comment by ManasaMS85** [comment]
@mattwiller - Any response on this code change

**Comment by mattwiller** [comment]
@ManasaMS85 Using the sample code you provided above, I am not able to reproduce the issue you're describing with a `.docx` file.  The completion handler is correctly called, and I'm able to pass the `BOXFile` to the Preview SDK and view the document.  Are you able to use a tool like [Charles Proxy](https://www.charlesproxy.com/) or [mitmproxy](https://mitmproxy.org/) to record API calls going in and out of your application?  That might help shed some light on exactly what's going on beneath the SDK.

The representations for a file are generated just one time, independent of the client requesting them.  A PDF representation definitely exists for that file, but I cannot determine which client made the request that started generation of the representation.  Once the representation is generated, any client will be able to see it.

**Comment by ManasaMS85** [comment]
@mattwiller - As per Varun's suggestion i changed the type to "BOXRepresentationHintsDefaultThumbnails" . and also set the fileRepresentationDownloadRequest representation to largeThumbnailRepresentation() and the preview image fetching worked
