### ISSUE TITLE
BOXContentClient logout

### ISSUE THREAD

**Issue by ManasaMS85** [box/box-ios-sdk#593]
is their a specific method to logout  - when using the appuser - instantiating a client using Server-to-Server auth.
i am doing  if let boxContentClientDefault = BOXContentClient.default() {
            boxContentClientDefault.logOut()
       }
     But this doesn't seem to logout the appuser . Is their anything i am missing in logout. 

My boxsdk instantiation is : 
  boxContentClient = BOXContentClient(for: authUser, initialToken: nil, fetchTokenBlockInfo: nil, fetchTokenBlock: fetchToken)!

**Comment by ManasaMS85** [comment]
@mattwiller  - Could you help with this issue . I tried boxContentClientDefault.logOut(), tried with the instance.logout and the static method - BOXContentClient.logoutall() 

None of them seem to work

**Comment by mattwiller** [comment]
@ManasaMS85 The default client and the client you instantiate are different — calling `.logOut()` on the default client will not log out your client.  If you created the client like `boxContentClient = BOXContentClient(for: authUser, initialToken: nil, fetchTokenBlockInfo: nil, fetchTokenBlock: fetchToken)!`, you'll want to call `boxContentClient.logOut()` instead.  That should revoke the access token being used and cancel any in-flight operations.

**Comment by ManasaMS85** [comment]
boxContentClient.logOut() also doesnot work - as the connected SDK instance is corrupted . We have sample app which we did for login and logout and we were able to see the sdk instance gets corrected . thats the same reason we have "unable to load image " issue as well.

Steps to reproduce 
1. Logout the app
2. login the app
3. Open box preview 
4. Logout again - the logout fails

**Comment by mattwiller** [comment]
@ManasaMS85 I'm able to reproduce the issue as you describe (thank you for the sample app!), and I'm in the process of investigating the issue.  In the meantime, I think it's likely that the issue might be due to your re-use of a single shared `boxContentClient` instance.  Could you try instantiating a new client using `BOXContentClient(for: authUser, initialToken: nil, fetchTokenBlockInfo: nil, fetchTokenBlock: fetchToken)` for each login instead of trying to re-authenticate the same client after it has been logged out?

**Comment by ManasaMS85** [comment]
@mattwiller  - For each new login i have been instantiating a new client - But unfortunately the previous logout does not work - this new instantiation does not seem to work perfectly. 

When i create a new instance of the client - unable to load image issue is resolved

**Comment by mattwiller** [comment]
@ManasaMS85 Can you explain a bit more what you mean by "the previous logout does not work"?  In your sample app, it does not appear that you're instantiating a new client at login — the code is re-authenticating the same client instance.

If creating a new instance of the client resolves your issue, is that an acceptable solution to this issue?

**Comment by PreciselyAlyss** [comment]
@ManasaMS85 Are you still running into this issue?
