### ISSUE TITLE
use of undeclared identifier 'SHA_DIGEST_LENGTH'

### ISSUE THREAD

**Issue by mdfalcon104** [box/box-ios-sdk#595]
Could you revise and fix on podspecs library.

**Comment by ghost** [comment]
See here is the answer #564. They don't support want to support CocoaPods. I change my projects to Carthage and it was not a lot of work.

**Comment by mdfalcon104** [comment]
@RWarnecke I've tried to added a cocoapod by myself but it is not luck. Do you know how to do that?

**Comment by mgrytsai** [comment]
Closing the issue due to inactivity. If you feel that we still need to look at it, please re-open the ticket.

A potential workaround is described here #564.
