### ISSUE TITLE
can I get the video url which can play directly?

### ISSUE THREAD

**Issue by wangshaoqi** [box/box-ios-sdk#610]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

Hi team 
   I have confusion about playing the video store in BOX. is there a way to get the video streamable URL to play directly? or some suggestions, please. or, it is only supported to paid user?
thanks a lot

**Comment by sujaygarlanka** [comment]
@wangshaoqi I believe HLS streams for videos are only provided for paid users. You can verify this for yourself by getting the representations for a file shown [here](https://developer.box.com/guides/representations/request-a-representation/). Pass `[hls]` to `x-rep-hints`.
