### ISSUE TITLE
Access to tags from iOS Content API

### ISSUE THREAD

**Issue by ezestkuldeep** [box/box-ios-sdk#62]
There is no option to access the tags for files and folders using iOS content SDK.

**Comment by boxtcarpel** [comment]
Thank you for reaching out and using the SDK. At this time, our current focus at Box is to enhance our 'Metadata' features rather than further investment in 'Tags'. Please check out the metadata functionality of the SDK to see if that fits your needs.

**Comment by boxtcarpel** [comment]
I'm going to close this issue for now. If you have further questions on this, please feel free to respond and reopen.
