### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by cvrattos** [box/box-ios-sdk#623]
I added the following lines to my as instructed in the github set up tutorial:

[[BOXContentClient defaultClient] authenticateWithCompletionBlock:^(BOXUser *user, NSError *error) {
        if (error == nil) {
            NSLog(@"Logged in user: %@", user.login);
        }
    } cancelBlock:nil];

However, I am unable to run my code because I have an "ARC semantic issue":

No visible @interface for 'BOXContentClient' declares the selector 'authenticateWithCompletionBlock:cancelBlock:'

**Comment by boxtcarpel** [comment]
@cvrattos the interface is just:
- (void)authenticateWithCompletionBlock:(void (^)(BOXUser *user, NSError *error))completion;

There is no cancel block for this approach. The set up guide is out of date and incorrect. We'll get that updated.

Apologies for the inconvenience. Dropping the cancelBlock: parameter should fix this issue for you!

Thanks for using the SDK
