### ISSUE TITLE
OneLogin  authentication redirection problem

### ISSUE THREAD

**Issue by leandrotha** [box/box-ios-sdk#661]
- [X] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
In order to access Box, users under our domain must authenticate through OneLogin. The BOX Login Webview then redirects our users to the OneLogin page to complete authentication. Sometimes, the Box SDK does not recognise that the auth has been completed and allows the user to navigate on the pages further on OneLogin platform. The occurrences of this issue seems to be random, some users are facing it and some are not. I was able to reproduce this myself a couple of times, but didn't find a pattern. In this cases that the issue occurs, the callback isn't called.

We're using the function <- (void)authenticateInAppWithCompletionBlock:(void (^)(BOXUser *user, NSError *error))completion;> to make the auth.

### Versions Used
Box Content SDK: 2.4.0
iOS: 11.4 (deployment); Tested on iOS 12 and above;

### Steps to Reproduce
Try to login on Box with a email domain that requires OneLogin Authentication.

### Error Message, Including Stack Trace
not applicable

**Comment by abhishek-bidgely** [comment]
@leandrotha were you able to fix this issue. I am also facing a similar intermittent issue in iOS.
