### ISSUE TITLE
UIWebView is deprecated

### ISSUE THREAD

**Issue by SergeiKu** [box/box-ios-sdk#669]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
UIWebView is deprecated but it is used in the framework. So I am getting messages from Apple that impose to switch to WKWebView.

### Versions Used
Box Content SDK: "v2.4.0"
iOS: 13

### Steps to Reproduce
Submit to Appstore the app which uses this framework.

### Error Message, Including Stack Trace
Dear Developer,
We identified one or more issues with a recent delivery for your app, "DocytStaging2" 3.2.1 (1153). Your delivery was successful, but you may wish to correct the following issues in your next delivery:
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.
Best regards,
The App Store Team

**Comment by jogu** [comment]
This was already mentioned here: https://github.com/box/box-ios-sdk/issues/647

The new box sdk (3.0) authored in Swift does not use UIWebView, but also does not appear to be directly usable in ObjC apps. 

The requirement from Apple is for existing apps to stop using UIWebView by December 2020:  https://developer.apple.com/news/?id=12232019b (and for new apps to stop by April 2020, however I would hope the majority of new apps are written in Swift and hence it's not a major issue to switch to the new SDK).

It would be great if the Box team can let us know if either:

1) The ObjC SDK is going to be updated to remove use of UIWebView

2) If the new SDK may gain compatibility with ObjC (for example creating a demo app for the SDK that's written in ObjC :-) )

Many thanks.
Joseph

**Comment by jiaohaibin** [comment]
Can we know the roadmap of removing UIWebView?
