### ISSUE TITLE
Carthage fails to install box-ios-sdk

### ISSUE THREAD

**Issue by brantonb** [box/box-ios-sdk#685]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/box/box-swift-sdk/blob/master/CONTRIBUTING.md).

## What did you do?

Our Carthage dependency manager stopped working in the past 48 hours with no changes in our project. We're using version 2.0.0 of the Box SDK, but I verified this is happening with 3.0.0 as well.

```
$ carthage update --platform iOS
*** Fetching box-ios-sdk
A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/box/box-ios-sdk.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (launched in /Users/bboehm/Library/Caches/org.carthage.CarthageKit/dependencies/box-ios-sdk)) failed with exit code 1
```

## What did you expect to happen?

Carthage installs per [the Readme instructions](https://github.com/box/box-ios-sdk#carthage).

## What happened instead?

Carthage failed to install the dependency in step 2 (when running `carthage update`).

## BoxSDK Environment

**BoxSDK version:** 2.0.0 and 3.0.0
**Xcode version:** N/A
**Swift version:** N/A
**Platform(s) running BoxSDK:** iOS
**macOS version running Xcode:** 10.14.6

**Comment by brantonb** [comment]
It appears this is caused when tags were modified somehow. There's [an open Carthage issue](https://github.com/Carthage/Carthage/issues/2786) about this, which pointed to [a work-around](https://github.com/ashleymills/Reachability.swift/issues/340):

```
$ rm -rf ~/Library/Caches/org.carthage.CarthageKit
```

After logging into all of our build machines and running this, we are able to build again.

**Comment by sujaygarlanka** [comment]
Glad it's working now. Thanks for posting the solution!
