### ISSUE TITLE
Detailed Documentation

### ISSUE THREAD

**Issue by adtechlab03** [box/box-ios-sdk#687]
Hello sir,

       We want to use this SDK. and I am a beginner level developer. so I need a detailed document on how to use this SDK in my projects. because when I use this SDK and implement the code whichever you provide in the readme file it's not working in my projects it's not finding get current user method.
 

So I would request to you please provide step by step guide so that I can use this SDK.

**Comment by carycheng** [comment]
Hey @adtechlab03,

Thank you for using the Box SDK. The question you submitted is a bit broad so let’s try to dig a bit deeper. Can you please let us know what exactly you are trying to do? Use case, your code snippet so far, and end goal would all be very helpful.

As for getting started, if you have taken a look at the readme, my next suggestion would be to skim through our developer docs here for [creating a client](https://github.com/box/box-ios-sdk/blob/master/docs/usage/authentication.md) and try to figure out which user type you would like to use, the developer account being the quickest and easiest to set up and hit the ground running but not great for production code or anything longer tailed. 

However, before you get started please give this a read [here](https://developer.box.com/en/guides/authentication/user-types/) regarding different user types, this might help you make a decision on which client best suites your use case.

After you have successfully selected a user type and created a client I would try a very simple call such as retrieving user information like this [one](https://github.com/box/box-ios-sdk/blob/master/docs/usage/users.md#get-user)

Lastly, all this is with the assumption you have an app set up. If not, please head on over [here](https://developer.box.com/en/guides/applications/custom-apps/jwt-setup/ ) to set up your application. The one step that seems to be missed that is worth calling out is please make sure to have you application authorized by the admin of the account in the enterprise settings -> app settings tab.

If you have any further questions please don’t hesitate to reach out.

**Comment by PJSimon** [comment]
@adtechlab03 I'm closing this issue as it appears resolved, but if you'd like to re-open it, please feel free to do so!  Thanks!
