### ISSUE TITLE
Full Documentation

### ISSUE THREAD

**Issue by devpetz007** [box/box-ios-sdk#688]
Hello Developer,

Can you please provide full documentation with a screenshot so we can easily implement it.

**Comment by carycheng** [comment]
Hey @devpetz007, 

We have full documentation with example usage and description of each endpoint [here](https://github.com/box/box-ios-sdk/tree/master/docs/usage). I would start with the read me [here](https://github.com/box/box-ios-sdk/blob/master/README.md) for set up. Let us know if this solves your question.

Thank you
