### ISSUE TITLE
Redirect URI between box ios sdk and box Rest Apis

### ISSUE THREAD

**Issue by nfz312** [box/box-ios-sdk#689]
Hi,
I need to way to set OAuth 2.0 Redirect URI valid for "box ios sdk" and ("box android sdk" or "box Rest Apis" )as my app work on multiple platforms,  that new redirect URL changed to:

> boxsdk-<< YOUR CLIENT ID >>://boxsdkoauth2redirect

As you know that Box not allow to set multiple redirect URIs.

**Comment by PJSimon** [comment]
Hi @nfz312,

Sorry for the delay.  My team is still catching up following the holidays!  We'll respond back to you soon!

Thanks!

Tracking: SDK-1252
