### ISSUE TITLE
'Dependency "box-ios-sdk" has no shared framework schemes' error when using Carthage

### ISSUE THREAD

**Issue by nhattieunhatkiem** [box/box-ios-sdk#69]
I got this error when using Carthage to build box-ios-sdk to framework. Is this a bug ?
Using CocoaPod to install box-ios-sdk with use_framework! config does not work too. File not found when I try to import BoxContentSDK.h file

**Comment by boxtcarpel** [comment]
@nhattieunhatkiem I think this pull request (https://github.com/box/box-ios-sdk/pull/70) should fix your CocoaPods issue.

I'm not sure about the Carthage error. We would need to look into that.

**Comment by nhattieunhatkiem** [comment]
New change still not work. I still got file not found error when trying this
#import <BoxContentSDK/BOXContentSDK.h>
@import box_ios_sdk does not work too. Can not find module.

About Carthage error, you can go here for detail:
https://github.com/Carthage/Carthage
1. Install Carthage
2. Create a Cartfile file with content:
   github "box/box-ios-sdk"
3. run 'carthage update'
   then you will get into that no shared framework error

**Comment by boxtcarpel** [comment]
Are you sure the new change was applied? We have not yet bumped the SDK version, so a pod update would not have pulled in this change.

**Comment by nhattieunhatkiem** [comment]
sorry, my bad. I changed my podfile to this
    pod 'box-ios-sdk', :git => 'https://github.com/box/box-ios-sdk.git'
and new changes were applied.

Everything work now. Thanks

**Comment by nhattieunhatkiem** [comment]
can you fix this issue in box-ios-browse-sdk too, I cannot include the header file into my project

BoxBrowseSDK/BoxBrowseSDK.h file not found

**Comment by boxtcarpel** [comment]
Yep, we're making the change in all of our SDKs. It's coming right up.
