### ISSUE TITLE
How to cancel a file download session

### ISSUE THREAD

**Issue by jiaohaibin** [box/box-ios-sdk#709]
## What did you do?

I use the following code to download a file
client.files.download(fileId: item.id, destinationURL: url, progress: { (progress) in
            progressCallback(Int(progress.completedUnitCount), Int(progress.totalUnitCount))
        }) { (result) in
            switch result {
            case .success(_):
                break
            case .failure(let error):
                break
            }
        }

## What did you expect to happen?

How to cancel this downloading session in the middle, when user pressed a cancel button.

## What happened instead?

if we do not cancel the downloading, the downloading will continue, it is not expected by user.

## BoxSDK Environment

**BoxSDK version: 4.0.0
**Xcode version: 11.4 beta2
**Swift version:5
**Platform(s) running BoxSDK:iOS
**macOS version running Xcode:10.15.3

## Demo Project

n/a

**Comment by PJSimon** [comment]
Hi @jiaohaibin!
This is an enhancement that we have on our backlog (SDK-981).  It's not currently prioritized very high, but due to your comments, I will try to get it bumped up! ;^)

**Comment by PJSimon** [comment]
Hi @jiaohaibin,

I just wanted to update you that this will be coming in the next few weeks!  We'll update here when it's merged.

Thanks for your patience!

PJSimon

**Comment by robertwijas** [comment]
All requests should handle cancellation. This seems like a **must have** feature for any network API.

**Comment by PJSimon** [comment]
Hi @jiaohaibin @robertwijas,
This is now available in the [latest version (v4.1.0)](https://github.com/box/box-ios-sdk/releases/tag/v4.1.0) of the iOS SDK!
Thanks!

**Comment by robertwijas** [comment]
@PJSimon thanks for the update!

My comment was more about the lack of cancellation in regular API calls. I'm glad that we can now cancel downloads/uploads, but I still think it should be possible to cancel API calls as well. This should be a separate issue though.
