### ISSUE TITLE
Adopt app written using 2.4.0 to 4.0.0???

### ISSUE THREAD

**Issue by darkForestCat** [box/box-ios-sdk#718]
## What did you do?

I was trying to upload a usual update of my app, but I can't do it anymore as 2.4.0 was using UIWebView, so I did an update to 4.0.0(Removing 2.4.0  framework installed with  Carthage and added  4.0.0 using CocoaPods)

## What did you expect to happen?

So I can finally upload my app without issues to  the App Store....

## What happened instead?

I found out that the framework is completely re-written and that my old FULLY WORKING CODE is not compatible with new version of the framework....

## So what is the question?

What I need to do in my  situation?Do I need to re-write all the stuff written before that is working perfectly or what?(It is real pain, impossible)

I think the best solution would be 2.4.0 with WKWebView,  how  could I use it inside my project  and is it available?I see there is still Obj-C support and even pull-request called  "Use WKWebView for authorization" but I don't understand how to use it, maybe someone can help me?

Example(I have a lot of stuff  written, it is just an example):

<img width="792" alt="Screenshot 2020-05-15 at 19 39 48" src="https://user-images.githubusercontent.com/25624923/82080029-22df7080-96e4-11ea-8088-048e3e5ac70b.png">

**Comment by PJSimon** [comment]
Hi @darkForestCat,

Sorry for the surprise about the migration of the box-ios-sdk from Objective-C to Swift, with [v3.0.0](https://github.com/box/box-ios-sdk/releases/tag/v3.0.0) in Nov 2019.

Per the repo's [README file](https://github.com/box/box-ios-sdk/blob/master/README.md):
>  The Box iOS SDK in **Objective-C** (prior to v3.0.0) has been moved from the master branch to the [objective-c-maintenance branch](https://github.com/box/box-ios-sdk/tree/objective-c-maintenance). Going forward, the master branch will contain the iOS SDK in **Swift**, starting with v3.0.0.

The good news is that the change to WKWebView was recently [committed](https://github.com/box/box-ios-sdk/pull/715) on the [objective-c-maintenance branch](https://github.com/box/box-ios-sdk/tree/objective-c-maintenance)!

Because the Objective-C code is "maintenance mode" we haven't cut a release with compiled binaries.  Are you able to do that yourself?

Thanks,

@PJSimon

**Comment by darkForestCat** [comment]
Resolved the issue by adding the framework to my project using Carthage like this:
`github "box/box-ios-sdk" "402fdf5"`
@PJSimon Thx for your  support!Hope I could upload the app without any issues to the App Store!

**Comment by darkForestCat** [comment]
I still get this error message when trying to upload my app.What can be the problem? 402fdf5 still contains UIWebView or what can it be?
<img width="746" alt="Screenshot 2020-05-15 at 22 32 52" src="https://user-images.githubusercontent.com/25624923/82093872-3c8cb200-96fc-11ea-9974-5f20b57742e1.png">

**Comment by darkForestCat** [comment]
@PJSimon Do  you know  what can cause this type of error?

**Comment by jogu** [comment]
@PJSimon 

> Because the Objective-C code is "maintenance mode" we haven't cut a release with compiled binaries. Are you able to do that yourself?

No need at all for compiled binaries - is it possible to publish a new podspec though please, i.e. just add the git sha for the new version to https://cocoapods.org/pods/box-ios-sdk ?
