### ISSUE TITLE
can not change redirectURI and nonce to custome variables

### ISSUE THREAD

**Issue by nhattieunhatkiem** [box/box-ios-sdk#72]
The box-ios-sdk only work when I create a new Box application with empty redirectURI, with current box app with an existing redirectURI, there is no way to get it work.

Also, is there anyway to get box credentialSecret and credentialToken returned after I logged in ? I need these values to perform Meteor login using Box Account.

Thanks.

**Comment by RicoYao** [comment]
Hi @nhattieunhatkiem 
1. For the redirectURI, you should set it to boxsdk-YOUR_CLIENT_ID://boxsdkoauth2redirect
   There's more detail about this here: https://github.com/box/box-ios-sdk/blob/master/doc/Setup.md#configure-your-application
2. Assuming you're referring to the refresh-token and access-token you can get it like this:

```
BOXContentClient *client = .... // your client
NSString *accessToken = ((BOXOAuth2Session *)client.session).accessToken;
NSString *refreshToken = ((BOXOAuth2Session *)client.session).refreshToken;
```

**Comment by nhattieunhatkiem** [comment]
Sorry I did not tell it clear.

My problem is I have an web app using Meteor framework that integrated with my Box app. And I use box accounts to login into my App (web and iOS). If I change my redirectURI to boxsdk-YOUR_CLIENT_ID://boxsdkoauth2redirect, my web app will not able to login anymore. That's why I need those credentialSecret and credentialToken values.

I can see that there is an option to set redirectURI for box android sdk, why does box ios sdk not have that ?
https://github.com/box/box-android-sdk
BoxConfig.CLIENT_ID = "your-client-id";
BoxConfig.CLIENT_SECRET = "your-client-secret";
// must match the redirect_uri set in your developer account if one has been set. Redirect uri should not be of type file:// or content://.
BoxConfig.REDIRECT_URL = "your-redirect-uri";

**Comment by RicoYao** [comment]
I've created a pull request to allow for customization of the redirect uri:
https://github.com/box/box-ios-sdk/pull/74

It would work like this:
[BOXCLient setClientID:@"client-id" clientSecret:@"client-secret" redirectURIString:@"redirectURIString"];

**Comment by nhattieunhatkiem** [comment]
Everything work fine now
It will be best if _nonce value contains loginStyle and credentialToken inside.

**Comment by nhattieunhatkiem** [comment]
Your new changes cause app fail to login. Can you check BOXAuthorizationViewController.m line 241. requestIsForLoginRedirectScheme is alway YES. It should only YES after server return Code value. OAuth2Session performAuthorizationCodeGrantWithReceivedURL run even code is undefined in URL.

**Comment by boxtcarpel** [comment]
Thanks for catching, @nhattieunhatkiem 
This is because having a redirect URI with a non-unique scheme (such as https://) was previously unexpected behavior. Now that the redirect URI can be set directly, that needs to be supported.

Please see https://github.com/box/box-ios-sdk/pull/77.

**Comment by nhattieunhatkiem** [comment]
I tested new change with this login code

```
[[BOXContentClient defaultClient] authenticateWithCompletionBlock:^(BOXUser *user, NSError *error) {
    if (error == nil) {
        NSLog(@"Logged in user: %@", user.modelID);
    } else {
        NSLog(@"error %@", error);
    }
}];
```

After fill login form and authorize It shows error instead of logged in user

**Comment by boxtcarpel** [comment]
Thanks for testing @nhattieunhatkiem (I was hoping you would). What is the error you are seeing?

In my tests auth was successful. If requestIsForLoginRedirection is getting the correct value now, then this might be a different (additional) issue.
