### ISSUE TITLE
Code signing "BoxContentSDK.framework" failed.

### ISSUE THREAD

**Issue by darkForestCat** [box/box-ios-sdk#720]
I am using Carthage and 2.4.0 "402fdf5" version of the framework.

## What did you do?

I was trying to upload my app to the App Store.

## What happened instead?

"Code signing "BoxContentSDK.framework" failed" error appeared:
<img width="747" alt="Screenshot 2020-05-16 at 17 22 49" src="https://user-images.githubusercontent.com/25624923/82124346-c68d5700-979e-11ea-9ef3-3179c002ae66.png">

Log:

`2020-05-16 16:39:22 +0000  /var/folders/6x/nc17_h0x35l9nmjh9_6z8scw0000gp/T/XcodeDistPipeline.~~~BvfTfv/Root/Payload/ATGoogleDriveDemo.app/Frameworks/BoxContentSDK.framework: code object is not signed at all
`

## What did you do to resolve the problem?
1)First of all I thought that the problem is that the SDK is using UIWebView, I have updated it using 402fdf5 commit so I can use it with WKWebView, but problem still appeared.
2)I have done search through stackoverflow and Carthage  git hub page and I am 99% sure that I done all the instructions of Carthage right.Here are the screenshots:
<img width="785" alt="Screenshot 2020-05-16 at 17 23 14" src="https://user-images.githubusercontent.com/25624923/82125004-3b629000-97a3-11ea-8245-d2f386fa5e6f.png">
<img width="780" alt="Screenshot 2020-05-16 at 17 23 36" src="https://user-images.githubusercontent.com/25624923/82125011-45848e80-97a3-11ea-8ddb-4693f118fd98.png">
3)I have re-installed the framework few times but it also has no result.
4)I  have also tried in "frameworks libraries and embedded content" to change "Embed" to all the possible states and  upload it with each of  them but it does not have any effect.
5)I saw that someone here had the same issue in "Closed issues", but the issue was that he did not use Carthage in the right way so it won't help me.

**Comment by PJSimon** [comment]
@darkForestCat I will try to reproduce, tomorrow.  I'll get back to you ASAP. 

Are you blocked? It sounds like you were able to upload your app to the app store, at least once. Are you no longer able to do so? 

When does the code signing error appear?

**Comment by darkForestCat** [comment]
@PJSimon adding after copy-frameworks script, from this answer (https://stackoverflow.com/questions/53050451/xcode-10-code-signing-my-appframework-fails-because-of-failure-signing-3rd-pa?answertab=votes#tab-top) resolved the issue, really strange things...

**Comment by PJSimon** [comment]
@darkForestCat Good news!  Glad to hear you are un-blocked!  And thanks for posting your resolution to potentially help others in the future!  We appreciate the contribution!  :^)
