### ISSUE TITLE
Get Box client synchronously

### ISSUE THREAD

**Issue by dabeku** [box/box-ios-sdk#725]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
Is it possible to get the box client (for production) synchronously?

Afaik BoxSDK.getClient(token: "YOUR_DEVELOPER_TOKEN") requires a token which is only valid for 1 hour. So this is only suitable during development and not suitable for a production app.

I have the following use-case: The app starts the first time - user logs in to Box (async via getOAuth2Client()) - gets redirected to app - app uses client. Then the user closes the app and restarts it. Imho it should be possible to get an instance of the logged in Box client so the app can use it without another call to getOAuth2Client().

In addition to this I need to check if the user is already linked to Box which could be done via the synchronous call (e.g. returns nil if not linked yet). Is there an official way to do this?

**Comment by PJSimon** [comment]
Hi @dabeku,

The Box iOS SDK uses a token store to do exactly what you describe.  Please check out the docs for more info: https://github.com/box/box-ios-sdk/blob/master/docs/usage/authentication.md#token-store

If that doesn't resolve your issue, please re-open this issue and we'll help further.

Thanks!
