### ISSUE TITLE
SDK Unable to Process Enterprise Events

### ISSUE THREAD

**Issue by stevebingsoo** [box/box-ios-sdk#727]
### Description of the Issue
When using the SDK to get enterprise events of type "SHARE", "UPLOAD", and possibly many other types of events, Box returns a http 200 response but the SDK throws a BoxCodingError

### Steps to Reproduce
Use the SDK to call getEnterpriseEvents and specify event type filters such as

`eventTypes: [.shareEnabled, .upload]`

### Expected Behavior
SDK should process all enterprise events successfully

### Error Message, Including Stack Trace
`
GET https://api.box.com/2.0/events?limit=1&event_type=SHARE&stream_type=admin_logs

Headers: 

    X-Box-UA, Value: agent=box-swift-sdk/1.0; env=iPhone Simulator/10.15.6

    Authorization, Value: Bearer **REDACTED**

Body:

2020-06-30 09:41:19.599226-0500 Box Shared Link Locator[72019:11540840] [NETWORK AGENT] 

Status code: 200: no error

Headers: 

    ◁ Date, Value: Tue, 30 Jun 2020 14:41:19 GMT

    ◁ Connection, Value: keep-alive

    ◁ Content-Encoding, Value: gzip

    ◁ Transfer-Encoding, Value: Identity

    ◁ Strict-Transport-Security, Value: max-age=31536000

    ◁ Content-Type, Value: application/json

    ◁ Cache-Control, Value: no-cache, no-store

    ◁ BOX-REQUEST-ID, Value: **REDACTED**

Body: {"chunk_size":1,"next_stream_position":"1152923066521988737","entries":[{"source":{"item_type":"file","item_id":"**REDACTED**","item_name":"wmt_h_r_4c.ai [wmt_h_r_4c.ai]","parent":{"type":"folder","name":"CMYK","id":"**REDACTED**"},"owned_by":{"type":"user","id":"**REDACTED**","name":"IT Services","login":"**REDACTED**"}},"created_by":{"type":"user","id":"**REDACTED**","name":"Laura Peppin","login":"**REDACTED**"},"action_by":null,"created_at":"2019-06-30T10:19:01-07:00","event_id":"c6441c96-c62d-4298-ab72-414d80743295","event_type":"SHARE","ip_address":"**REDACTED**","type":"event","session_id":null,"additional_details":{"shared_link_id":"**REDACTED**","size":60410,"file_path":"\/Client Folders\/Clients - Walmart\/01_LOGOS-FONTS\/Walmart Logos\/AI Format\/CMYK","file_hash":"**REDACTED**","hash_type":"sha1","version_id":"488501651752"}}]}

{

  "error" : "Value for key type was of an unexpected type",

  "errorType" : "BoxCodingError",

  "message" : "Error with encoding or decoding",

  "stackTrace" : [

    "0   Box Shared Link Locator             0x00000001000585b1 $s6BoxSDK0A8SDKErrorC7message5errorAcA0aC4EnumO_s5Error_pSgtcfc + 433",

    "1   Box Shared Link Locator             0x0000000100052245 $s6BoxSDK0A11CodingErrorC7message5errorAcA0A12SDKErrorEnumO_s0D0_pSgtcfc + 101",

    "2   Box Shared Link Locator             0x00000001000521d7 $s6BoxSDK0A11CodingErrorC7message5errorAcA0A12SDKErrorEnumO_s0D0_pSgtcfC + 55",

    "3   Box Shared Link Locator             0x000000010012dd88 $s6BoxSDK18ObjectDeserializerO11deserialize4datas6ResultOyxAA0A8SDKErrorCG10Foundation4DataVSg_tAA0A5ModelRzlFZ + 2872",

    "4   Box Shared Link Locator             0x000000010012fbee $s6BoxSDK14PagingIteratorC8response6clientACyxGAA0A8ResponseV_AA0A6ClientCtKcfc + 1054",

    "5   Box Shared Link Locator             0x000000010012f77f $s6BoxSDK14PagingIteratorC8response6clientACyxGAA0A8ResponseV_AA0A6ClientCtKcfC + 95",

    "6   Box Shared Link Locator             0x0000000100074c5e $s6BoxSDK15ResponseHandlerO14pagingIterator6client8wrappingys6ResultOyAA0aC0VAA0A8SDKErrorCGcAA0A6ClientC_yAHyAA06PagingF0CyxGALGctAA0A5ModelRzlFZyAMcfU_ + 702",

    "7   Box Shared Link Locator             0x00000001000390d8 $s6BoxSDK0A6ClientC16handleAuthIssues33_BD010A8A97994AA2B669A3BAC1EE9CF4LL6result10completionys6ResultOyAA0A8ResponseVAA0A8SDKErrorCG_yANctF + 600",

    "8   Box Shared Link Locator             0x0000000100038e63 $s6BoxSDK0A6ClientC4send33_BD010A8A97994AA2B669A3BAC1EE9CF4LL7request10completionyAA0A7RequestC_ys6ResultOyAA0A8ResponseVAA0A8SDKErrorCGctFyAKySSAOGcfU_yAPcfU_ + 323",

    "9   Box Shared Link Locator             0x0000000100129e11 $s6BoxSDK0A12NetworkAgentC15processResponse_10retryCount0G010completionyAA0aF0V_Siyycys6ResultOyAiA0A8SDKErrorCGctF + 3009",

    "10  Box Shared Link Locator             0x00000001001245bd $s6BoxSDK0A12NetworkAgentC4send33_A624A9A39B9748FB6A6B2B4EF49B19D4LL7request10retryCount10completionyAA0A7RequestC_Siys6ResultOyAA0A8ResponseVAA0A8SDKErrorCGctFy10Foundation4DataVSg_So13NSURLResponseCSgs5Error_pSgtcfU_ + 1405",

    "11  Box Shared Link Locator             0x000000010012c28a $s6BoxSDK0A12NetworkAgentC4send33_A624A9A39B9748FB6A6B2B4EF49B19D4LL7request10retryCount10completionyAA0A7RequestC_Siys6ResultOyAA0A8ResponseVAA0A8SDKErrorCGctFy10Foundation4DataVSg_So13NSURLResponseCSgs5Error_pSgtcfU_TA + 58",

    "12  Box Shared Link Locator             0x0000000100124cd8 $s10Foundation4DataVSgSo13NSURLResponseCSgs5Error_pSgIegggg_So6NSDataCSgAGSo7NSErrorCSgIeyByyy_TR + 296",

    "13  CFNetwork                           0x00007fff31a6fcca CFURLCredentialStorageCopyAllCredentials + 24894",

    "14  CFNetwork                           0x00007fff319bd938 CFURLRequestGetMainDocumentURL + 15849",

    "15  Foundation                          0x00007fff358c8ac5 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7",

    "16  Foundation                          0x00007fff358c89e6 -[NSBlockOperation main] + 80",

    "17  Foundation                          0x00007fff358c8981 __NSOPERATION_IS_INVOKING_MAIN__ + 17",

    "18  Foundation                          0x00007fff358c7bb3 -[NSOperation start] + 722",

    "19  Foundation                          0x00007fff358c78d9 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 17",

    "20  Foundation                          0x00007fff358c77a9 __NSOQSchedule_f + 182",

    "21  libdispatch.dylib                   0x00000001008e6cd2 _dispatch_block_async_invoke2 + 83",

    "22  libdispatch.dylib                   0x00000001008d6826 _dispatch_client_callout + 8",

    "23  libdispatch.dylib                   0x00000001008d967d _dispatch_continuation_pop + 585",

    "24  libdispatch.dylib                   0x00000001008d8771 _dispatch_async_redirect_invoke + 769",

    "25  libdispatch.dylib                   0x00000001008ea391 _dispatch_root_queue_drain + 334",

    "26  libdispatch.dylib                   0x00000001008eae03 _dispatch_worker_thread2 + 127",

    "27  libsystem_pthread.dylib             0x000000010096431b _pthread_wqthread + 220",

    "28  libsystem_pthread.dylib             0x000000010096349b start_wqthread + 15"
  ]
}
`

### Versions Used
iOS SDK: master and v4.1
iOS: 13.5 but the version doesn't seem to matter
Xcode: 11.5

**Comment by sujaygarlanka** [comment]
@stevebingsoo This is an issue with the SDK. We are looking into pushing a fix for this soon.

**Comment by stevebingsoo** [comment]
The fix works great.  thanks!
