### ISSUE TITLE
How to disable BoxNetworkAgent logging?

### ISSUE THREAD

**Issue by robertwijas** [box/box-ios-sdk#733]
`BoxNetworkAgent` logs a ton of stuff in `DEBUG`. **Is there a way to disable that?**

`ConsoleLogDestination` loggers are private and I cannot subclass to pass my own implementation because it's not an  _open_ class.

The API would work just fine if `BoxSDKConfiguration.consoleLogDestination` type was changed to `LogDestination` instead of the final `ConsoleLogDestination` class (and `BoxSDK.updateConfiguration` _consoleLogDestination_ param type should be changed accordingly).

BoxSDK version 4.1.0.

**Comment by sujaygarlanka** [comment]
@robertwijas We have ticket open to address custom logging within the iOS SDK. We are looking to get to it within the next few weeks. Will keep you up to date on any progress made with this. Thanks!

**Comment by sujaygarlanka** [comment]
Internal Jira Ticket: SDK-744
