### ISSUE TITLE
Error when running the code

### ISSUE THREAD

**Issue by jpabanil** [box/box-ios-sdk#735]
Hello,

Got this error when running the code.
Error Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=2 "Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start." UserInfo={NSDebugDescription=Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start.

Code is
let sdk = BoxSDK(clientId: clientId, clientSecret: clientSecret)
        //var mClient: BoxClient!
        sdk.getOAuth2Client() { result in
            switch result {
            case let .success(client):
                SVProgressHUD.showSuccess(withStatus: "Success! App is now linked to your Box account.")
            case let .failure(error):
                print(error)
                SVProgressHUD.showError(withStatus: "Error: \(error)")
            }
        }

Pls help.. Need this asap

**Comment by sujaygarlanka** [comment]
@jpabanil I would take a look at our OAuth2 sample app. It already has OAuth working. I would either use that as a start to your app or copy and paste the OAuth code into your app. https://github.com/box/box-ios-sdk/tree/master/SampleApps/OAuth2SampleApp. If this does not solve your issue, feel free to re-open this.

**Comment by jpabanil** [comment]
Its not working :(

**Comment by sujaygarlanka** [comment]
@jpabanil Did you follow the instructions here https://github.com/box/box-ios-sdk#oauth2-sample-app?
