### ISSUE TITLE
Refresh token is failing with 401 error code.

### ISSUE THREAD

**Issue by prasad1240** [box/box-ios-sdk#744]
Authentication Method: User Authentication(OAuth 2.0)
SDK:  iOS Box SDK
Version: 4.2.0
Custom Token info: Yes
Xcode: 12.0.1

**Code:-**
`if let oAuthSession:OAuth2Session = self.client.session as? OAuth2Session {
                            oAuthSession.refreshToken { result in
                                        switch result {
                                        case let .success(token):
                                            expect(token).to(equal("new access token"))
                                        case let .failure(error):
                                            fail("refreshToken should succeed, but instead got \(error)")
                                        }
                                        done()
                                    }
                            }`

After 24 hours, Refresh token is failing with 401 error code. What is the best practice for iOS SDK refresh token? 

Please guide me.

Thanks,
Prasad

**Comment by prasad1240** [comment]
@sujaygarlanka , @PJSimon 
Any update on this please?

**Comment by MirceaX2Mobile** [comment]
I have the same issue, I can't refresh the token after 24 hours. Im creating a TokenInfo and then after getting the OAuth2Client and im calling refreshToken method from the currentSession, but it's failing with "token is expired".
