### ISSUE TITLE
Getting redirect URI missing error

### ISSUE THREAD

**Issue by bawanevaibhavi** [box/box-ios-sdk#752]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Versions Used
iOS SDK: 
iOS Preview SDK: 
iOS: 
Xcode: 

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by bawanevaibhavi** [comment]
![Screenshot 2021-02-05 at 5 16 27 PM](https://user-images.githubusercontent.com/30460869/107030217-4d271000-67d6-11eb-8a9d-2e43dad544ea.png)

**Comment by sujaygarlanka** [comment]
@bawanevaibhavi Did you follow the steps [here](https://github.com/box/box-ios-sdk#oauth2-sample-app)? Also, did you set the url in the developer console?

**Comment by bawanevaibhavi** [comment]
I am getting this issue/error in running AppStore application. It was working earlier.

**Comment by swfree** [comment]
Hi @bawanevaibhavi,

There was a change at the end of last year to require a Redirect URI for OAuth 2 Box Apps. Check out the post here for more context and for steps on how to update your application to fix the error you are seeing: https://developer.box.com/changelog/#2020-12-14-blank-oauth2-redirect-uri-change.

Impacted applications would have received emails to the developer email address associated with the application and account. You may want to make sure the email address in your application is up-to-date, to receive any similar communications in the future.

@swfree
