### ISSUE TITLE
Misuse of `callbackURLScheme` argument in iOS Authentication API

### ISSUE THREAD

**Issue by hironytic** [box/box-ios-sdk#754]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
When using OAuth2 Authentication on iOS, a whole redirect URL is eventually passed to an initializer of `ASWebAuthenticationSession` / `SFAuthenticationSession`, as a second argument (`callbackURLScheme`).
But the parameter `callbackURLScheme` is supposed to accept only scheme, not the whole URL.

e.g.
- 🙅 `boxsdk-vvxff7v61xi7gqveejo8jh9d2z9xhox5://boxsdkoauth2redirect`
- 🙆 `boxsdk-vvxff7v61xi7gqveejo8jh9d2z9xhox5`

If only the scheme is passed correctly, there is no need to add `CFBundleURLTypes` key into Info.plist.

### Steps to Reproduce
1. Remove `CFBundleURLTypes` key in Info.plist.
2. Call `BoxClient.getOAuth2Client(tokenInfo:tokenStore:context:completion:)`.
3. Log in to Box, then click "Grant access to Box"
4. An error message "Safari cannot open the page because the address is invalid." appears.

### Expected Behavior
No error occurs.

### Versions Used
Box SDK: 4.3.0
iOS SDK: 14.4
iOS: 14.4 or 11.4
Xcode: 12.4

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by swfree** [comment]
Hi @hironytic,

Thanks for reporting this issue and putting up the PR! The fix looks good, we'll work on getting that merged in.

@swfree
