### ISSUE TITLE
Need Help For Integration 

### ISSUE THREAD

**Issue by gopalIOS1989** [box/box-ios-sdk#780]
I have added Pod in My Objective c.
Import BoxSdk 
But Not Getting Any Function. means BooxSDK getClient ...

**Comment by jlawton** [comment]
Hi @gopalIOS1989.

As of version 3, this SDK has been designed for use in Swift codebases, and is not compatible with Objective-C. This represents the significant majority of apps newly adopting the SDK.

You might look at the [objective-c-maintenance](/box/box-ios-sdk/tree/objective-c-maintenance) branch. I believe the latest Objective-C compatible release was [v2.4.0](/box/box-ios-sdk/releases/tag/v2.4.0). An alternative approach, if you need to use the very latest Box APIs, would be to access the SDK from Swift and expose relevant functions to Objective-C from there.

I hope one of those paths helps.

**Comment by gopalIOS1989** [comment]
![Screenshot 2021-07-08 at 3 05 31 PM](https://user-images.githubusercontent.com/76942495/124899798-1744bc80-dffe-11eb-8ad6-89530f76ae35.png)

We are not able to install framework using Carthage. Attached error and is there any other way to use your objective-c SDK (2.4.0) like using pod?

**Comment by jlawton** [comment]
Does the `--use-xcframeworks` flag mentioned in the error help? It should alternatively be possible to drag the framework project into your project and add it as a target dependency for your app.

**Comment by arjankowski** [comment]
Hi @gopalIOS1989, 

Do you still need any help with this issue?
Have you tried `--use-xcframeworks` flag already?
