### ISSUE TITLE
Adding native visionOS Support. Error compiling

### ISSUE THREAD

**Issue by BhavinPat** [box/box-ios-sdk#915]
### Is your feature request related to a problem? Please describe.

When compiling Box SDK for native visionOS specifically in the AnalyticsHeaderGenerator class. There is no statements to handle visionOS os devices. 

### Describe alternatives you've considered

I have considered creating a fork and updating the code to support visionOS. But I would prefer if you'll be able to update the code. 

Attached is a screenshot of the errors in the AnalyticsHeaderGenerator.swift file. There may be more instances in other parts of the Box SDK. But I haven't found them all yet. 

<img width="728" alt="Screenshot 2024-02-28 at 1 31 09 PM" src="https://github.com/box/box-ios-sdk/assets/64485115/2bfb8b11-625e-48bf-b527-5785b0370827">

**Comment by arjankowski** [comment]
Hi @BhavinPat, thanks for reporting the issue!
I've created a task for the problem you described in our internal Jira(SDK-3661), and we'll address it soon.
May I ask how you integrate with our SDK? Is it through SPM, CocoaPods, or perhaps Carthage?

**Comment by BhavinPat** [comment]
I'm using SPM.

**Comment by BhavinPat** [comment]
Is there a timeline to when these changes will be incorporated?

**Comment by arjankowski** [comment]
Hi @BhavinPat, 
We have already released a new version of ios sdk ,`5.6.0`, where we added support for VisionOS.
Please let us know if everything works as expected.

Regards,
Artur
