### ISSUE TITLE
Unable to add SPM

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [box/box-ios-sdk#918]
Xcode -> Add Package Dependencies  https://github.com/box/box-ios-sdk

Result: 

![Screenshot](https://github.com/box/box-ios-sdk/assets/3391456/faea1223-9166-4ad6-84ac-5bb8f45b24ce)

**Comment by arjankowski** [comment]
Hi @Volodymyr-13, thanks for reporting the issue.
For some reason, the default SPM version is set to `1.0.0` but we'll fix it soon.
In the meantime, if you want to add the SDK using SPM, please set `Up to Next Major Version` to 5.0.0 < 6.0.0. This way, you'll install the correct package.

Regards,
Artur

**Comment by arjankowski** [comment]
It should work now and point to the current version 5.5.0
