### ISSUE TITLE
PrivacyInfo.xcprivacy support

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [box/box-ios-sdk#923]
All SDK's now should support a PrivacyInfo.xcprivacy file.. 

https://developer.apple.com/videos/play/wwdc2023/10060/
https://developer.apple.com/news/?id=av1nevon
https://developer.apple.com/app-store/user-privacy-and-data-use/

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by congminh1254** [comment]
Hi @Volodymyr-13 

Thanks for your information, we are working on it.

Bests,
Minh Nguyen Cong

**Comment by Anywhere-Music-Player** [comment]
Thank, hope to new SDK release with all new fixes and improvements.
