### ISSUE TITLE
How to disable Logs: "◁ Status code: 200: no error ◁ Headers: ........" 

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [box/box-ios-sdk#926]
When using Box SDK I see a lot of logs like: 
```
▷ GET https://api.box.com/2.0/users/me?
▷ Headers: 
    ▷ X-Box-, Value: agent=box-swift-sdk/0.8.6; env=iPhone14,2/17.5
    ▷ Authorization, Value: Bearer 5he9Ni0000000000000000
▷ Body:

◁ Status code: 200: no error
◁ Headers: 
    ◁ Alt-Svc, Value: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
    ◁ Cache-Control, Value: no-cache, no-store
    ◁ Via, Value: 1.1 google
    ◁ Date, Value: Sun, 14 Apr 2024 10:33:06 GMT
    ◁ x-envoy-upstream-service-time, Value: 89
    ◁ Content-Type, Value: application/json
    ◁ Strict-Transport-Security, Value: max-age=31536000
    ◁ box-request-id, Value: 0900000000000000000000
◁ Body: {"type":"user","id":"32352335607","name":"00000000","login":"000000000@gmail.com","created_at":"2024-03-05T11:05:08-08:00","modified_at":"2024-04-11T06:26:34-07:00","language":"en","timezone":"America\/Los_Angeles","space_amount":10737418240,"space_used":190707834,"max_upload_size":262144000,"status":"active","job_title":"","phone":"","address":"","avatar_url":"https:\/\/app.box.com\/api\/avatar\/large\/32000000000","notification_email":null}

```

### Describe the solution you'd like
I want to disable such logs.

**Comment by mhagmajer** [comment]
Unfortunately, the Box iOS SDK doesn't provide a direct way to control the logging level in its public API.

A workaround is to disable logging for the entire application by setting the logging level of the system's shared logger to a level that suppresses these logs. Here's an example of how you can achieve this:

```swift
import os.log

// Disable logs for the entire application
os_log.setLogger(nil)
```

This code sets the application's shared logger to nil, effectively disabling logging. However, keep in mind that this approach disables logging for the entire application, not just for the Box iOS SDK. If you have other logging requirements, you may need to explore alternative solutions, such as filtering out Box SDK logs using a custom logging system or wrapper.

**Comment by Anywhere-Music-Player** [comment]
@mhagmajer but any other SDK’s has logging level option, so this is like a requirement. Why this ignored here..?
