### ISSUE TITLE
how to get streaming video URL from Box via ios BoxSDK 5.6.0

### ISSUE THREAD

**Issue by PJStation** [box/box-ios-sdk#929]
how to get streaming video URL from Box via ios BoxSDK 5.6.0

**Comment by mwwoda** [comment]
Hi @PJStation 
If you want to get URL and e.g. embed it on your page you can use [getEmbedLink](https://github.com/box/box-ios-sdk/blob/main/docs/usage/files.md#get-file-embed-link) function. Alternatively, you could look into [shared links](https://github.com/box/box-ios-sdk/blob/main/docs/usage/files.md#get-shared-link) if they fit your use case.

**Comment by EZPlayerBusiness** [comment]
> Hi @PJStation If you want to get URL and e.g. embed it on your page you can use [getEmbedLink](https://github.com/box/box-ios-sdk/blob/main/docs/usage/files.md#get-file-embed-link) function. Alternatively, you could look into [shared links](https://github.com/box/box-ios-sdk/blob/main/docs/usage/files.md#get-shared-link) if they fit your use case.
1. [getEmbedLink](https://github.com/box/box-ios-sdk/blob/main/docs/usage/files.md#get-file-embed-link) 
Link cannot be played
2. [shared links](https://github.com/box/box-ios-sdk/blob/main/docs/usage/files.md#get-shared-link) rerturn failure

**Comment by PJStation** [comment]
> Hi @PJStation If you want to get URL and e.g. embed it on your page you can use [getEmbedLink](https://github.com/box/box-ios-sdk/blob/main/docs/usage/files.md#get-file-embed-link) function. Alternatively, you could look into [shared links](https://github.com/box/box-ios-sdk/blob/main/docs/usage/files.md#get-shared-link) if they fit your use case.

[getEmbedLink](https://github.com/box/box-ios-sdk/blob/main/docs/usage/files.md#get-file-embed-link)
Link cannot be played
[shared links](https://github.com/box/box-ios-sdk/blob/main/docs/usage/files.md#get-shared-link) rerturn failure

**Comment by mwwoda** [comment]
Could you provide more details about what you are trying to achieve? Perhaps you could also provide an sample code (example project) so we can see what's the issue.

**Comment by PJStation** [comment]
> Could you provide more details about what you are trying to achieve? Perhaps you could also provide an sample code (example project) so we can see what's the issue.


```
//get a mp4 file
client.files.getEmbedLink(forFile: file.id) { result in
    switch result {
    case let .success(expiringEmbedLink):
        var options = [String : Any]()
        options["AVURLAssetHTTPHeaderFieldsKey"] = ["Authorization": "Bearer \(expiringEmbedLink.token!.accessToken!)"]
        let asset = AVURLAsset(url: expiringEmbedLink.url!,options: options)

        if asset.isPlayable {
            print("isPlayable")
        } else {
            print("not playable")
        }
        
        break
    case let .failure(error):
        break
    }

}
```
isPlayable always false

**Comment by congminh1254** [comment]
Hi @PJStation 

Can you try with this url scheme: `https://api.box.com/2.0/files/:file_id:/content` and attach with your access token in the header.

<img width="1099" alt="image" src="https://github.com/box/box-ios-sdk/assets/9329079/97542d74-eed6-48b0-bfef-fe7b3464c884">

Let me know if it's working.

Best,
Minh

**Comment by PJStation** [comment]
> https://api.box.com/2.0/files/:file_id:/content
Thanks,it's working!
